/* Automatically generated by
        VMPluginCodeGenerator VMMaker.oscog-eem.3634 uuid:
   8a640496-a277-4c3e-be09-22770a14fb3c
        (* Compiler-ct.519)
   from
        BalloonEnginePlugin VMMaker.oscog-eem.3634 uuid:
   8a640496-a277-4c3e-be09-22770a14fb3c
 */
#if defined(__clang__) || defined(__GNUC__)
static const char __buildInfo[] __attribute__((unused)) =
    "BalloonEnginePlugin VMMaker.oscog-eem.3634 uuid: "
    "8a640496-a277-4c3e-be09-22770a14fb3c " __DATE__;
#else
static const char __buildInfo[] =
    "BalloonEnginePlugin VMMaker.oscog-eem.3634 uuid: "
    "8a640496-a277-4c3e-be09-22770a14fb3c " __DATE__;
#endif

#include "config.h"
#include "sqMathShim.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"           /* Configuration options */
#include "sqPlatformSpecific.h" /* Platform specific definitions */
#include "sqVirtualMachine.h"   /*  The virtual machine proxy definition */

#include "sqMemoryAccess.h"

#define true 1
#define false 0
#define null 0 /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
#define EXPORT(returnType) static returnType
#define INT_EXT "(i)"
#else
#define INT_EXT "(e)"
#endif

/*** Constants ***/
#define BEBalloonEngineSize 12
#define BEBitBltIndex 2
#define BEFormsIndex 3
#define BESpanIndex 1
#define BEWorkBufferIndex 0
#define ETBalloonEdgeDataSize 6
#define ETIndexIndex 0
#define ETLinesIndex 4
#define ETXValueIndex 1
#define ETYValueIndex 2
#define ETZValueIndex 3
#define FTBalloonFillDataSize 6
#define FTIndexIndex 0
#define FTMaxXIndex 2
#define FTMinXIndex 1
#define FTYValueIndex 3
#define GBBaseSize 16
#define GBBitmapDepth 12
#define GBBitmapHeight 11
#define GBBitmapRaster 14
#define GBBitmapSize 13
#define GBBitmapWidth 10
#define GBColormapOffset 18
#define GBColormapSize 15
#define GBEndX 14
#define GBEndY 15
#define GBFinalX 21
#define GBMBaseSize 18
#define GBTileFlag 16
#define GBUpdateData 10
#define GBUpdateDDX 4
#define GBUpdateDDY 5
#define GBUpdateDX 2
#define GBUpdateDY 3
#define GBUpdateX 0
#define GBUpdateY 1
#define GBViaX 12
#define GBViaY 13
#define GBWideEntry 18
#define GBWideExit 19
#define GBWideExtent 20
#define GBWideFill 16
#define GBWideSize 28
#define GBWideUpdateData 22
#define GBWideWidth 17
#define GEBaseEdgeSize 10
#define GEBaseFillSize 4
#define GEEdgeFillsInvalid 0x10000
#define GEFAlreadyFailed 100
#define GEFBadPoint 121
#define GEFBitBltLoadFailed 122
#define GEFClassMismatch 114
#define GEFEdgeDataTooSmall 112
#define GEFEngineIsInteger 101
#define GEFEngineIsWords 102
#define GEFEngineStopped 104
#define GEFEngineTooSmall 103
#define GEFEntityCheckFailed 120
#define GEFEntityLoadFailed 119
#define GEFFillDataTooSmall 113
#define GEFFormLoadFailed 123
#define GEFillIndexLeft 8
#define GEFillIndexRight 9
#define GEFSizeMismatch 115
#define GEFWorkBufferBadMagic 108
#define GEFWorkBufferIsInteger 105
#define GEFWorkBufferIsPointers 106
#define GEFWorkBufferStartWrong 110
#define GEFWorkBufferTooSmall 107
#define GEFWorkBufferWrongSize 109
#define GEFWorkTooBig 111
#define GEFWrongEdge 118
#define GEFWrongFill 117
#define GEFWrongState 116
#define GENumLines 7
#define GEObjectIndex 2
#define GEObjectLength 1
#define GEObjectType 0
#define GEPrimitiveBezier 6
#define GEPrimitiveClippedBitmapFill 0x400
#define GEPrimitiveEdge 2
#define GEPrimitiveEdgeMask 0xFF
#define GEPrimitiveFill 0x100
#define GEPrimitiveFillMask 0xFF00
#define GEPrimitiveLine 4
#define GEPrimitiveLinearGradientFill 0x200
#define GEPrimitiveRadialGradientFill 0x300
#define GEPrimitiveTypeMask 0xFFFF
#define GEPrimitiveWide 1
#define GEPrimitiveWideBezier 7
#define GEPrimitiveWideLine 5
#define GEPrimitiveWideMask 0xFE
#define GErrorAETEntry 6
#define GErrorBadState 2
#define GErrorFillEntry 5
#define GErrorGETEntry 4
#define GErrorNeedFlush 3
#define GErrorNoMoreSpace 1
#define GEStateAddingFromGET 1
#define GEStateBlitBuffer 5
#define GEStateCompleted 8
#define GEStateScanningAET 3
#define GEStateUnlocked 0
#define GEStateUpdateEdges 6
#define GEStateWaitingChange 7
#define GEStateWaitingForEdge 2
#define GEStateWaitingForFill 4
#define GEXValue 4
#define GEYValue 5
#define GEZValue 6
#define GFDirectionX 6
#define GFDirectionY 7
#define GFNormalX 8
#define GFNormalY 9
#define GFOriginX 4
#define GFOriginY 5
#define GFRampLength 10
#define GFRampOffset 12
#define GGBaseSize 12
#define GLBaseSize 16
#define GLEndX 14
#define GLEndY 15
#define GLError 13
#define GLErrorAdjDown 15
#define GLErrorAdjUp 14
#define GLWideEntry 18
#define GLWideExit 19
#define GLWideExtent 20
#define GLWideFill 16
#define GLWideSize 21
#define GLWideWidth 17
#define GLXDirection 10
#define GLXIncrement 12
#define GLYDirection 11
#define GWAAColorMask 0x33
#define GWAAColorShift 50
#define GWAAHalfPixel 53
#define GWAALevel 48
#define GWAAScanMask 0x34
#define GWAAShift 49
#define GWAETStart 13
#define GWAETUsed 14
#define GWBezierHeightSubdivisions 109
#define GWBezierLineConversions 111
#define GWBezierMonotonSubdivisions 108
#define GWBezierOverflowSubdivisions 110
#define GWBufferTop 10
#define GWClearSpanBuffer 69
#define GWClipMaxX 43
#define GWClipMaxY 45
#define GWClipMinX 42
#define GWClipMinY 44
#define GWColorTransform 24
#define GWCountAddAETEntry 97
#define GWCountChangeAETEntry 107
#define GWCountDisplaySpan 103
#define GWCountFinishTest 93
#define GWCountInitializing 91
#define GWCountMergeFill 101
#define GWCountNextAETEntry 105
#define GWCountNextFillEntry 99
#define GWCountNextGETEntry 95
#define GWCurrentY 88
#define GWCurrentZ 113
#define GWDestOffsetX 46
#define GWDestOffsetY 47
#define GWEdgeTransform 18
#define GWFillMaxX 37
#define GWFillMaxY 39
#define GWFillMinX 36
#define GWFillMinY 38
#define GWGETStart 11
#define GWGETUsed 12
#define GWHasColorTransform 17
#define GWHasEdgeTransform 16
#define GWHeaderSize 128
#define GWLastExportedEdge 65
#define GWLastExportedFill 66
#define GWLastExportedLeftX 67
#define GWLastExportedRightX 68
#define GWMagicIndex 0
#define GWMagicNumber 1097753705
#define GWMinimalSize 256
#define GWNeedsFlush 63
#define GWObjStart 8
#define GWObjUsed 9
#define GWPoint1 80
#define GWPoint2 82
#define GWPoint3 84
#define GWPoint4 86
#define GWSize 1
#define GWSpanEnd 34
#define GWSpanEndAA 35
#define GWSpanSize 33
#define GWSpanStart 32
#define GWState 2
#define GWStopReason 64
#define GWTimeAddAETEntry 96
#define GWTimeChangeAETEntry 106
#define GWTimeDisplaySpan 102
#define GWTimeFinishTest 92
#define GWTimeInitializing 90
#define GWTimeMergeFill 100
#define GWTimeNextAETEntry 104
#define GWTimeNextFillEntry 98
#define GWTimeNextGETEntry 94

/*** Function Prototypes ***/
static sqInt accurateLengthOfwith(sqInt deltaX, sqInt deltaY);
static sqInt addEdgeToGET(sqInt edge);
static sqInt adjustWideBezierLeftwidthoffsetendX(sqInt bezier, sqInt lineWidth,
                                                 sqInt lineOffset, sqInt endX);
static sqInt adjustWideBezierRightwidthoffsetendX(sqInt bezier, sqInt lineWidth,
                                                  sqInt lineOffset, sqInt endX);
static sqInt adjustWideLineafterSteppingFromto(sqInt line, sqInt lastX,
                                               sqInt nextX);
static sqInt allocateGETEntry(sqInt nSlots);
static sqInt allocateObjEntry(sqInt nSlots);
static sqInt checkCompressedFillIndexListmaxsegments(sqInt fillList,
                                                     sqInt maxIndex,
                                                     sqInt nSegs);
static sqInt checkCompressedFills(sqInt indexList);
static int checkCompressedLineWidthssegments(sqInt lineWidthList,
                                             sqInt nSegments);
static sqInt checkCompressedPointssegments(sqInt points, sqInt nSegments);
static sqInt
checkCompressedShapesegmentsleftFillsrightFillslineWidthslineFillsfillIndexList(
    sqInt points, sqInt nSegments, sqInt leftFills, sqInt rightFills,
    sqInt lineWidths, sqInt lineFills, sqInt fillIndexList);
static double *circleCosTable(void);
static double *circleSinTable(void);
static sqInt clearSpanBuffer(void);
static int computeBezierSplitAtHalf(sqInt index);
static int computeBeziersplitAt(sqInt index, double param);
static sqInt computeFinalWideBezierValueswidth(sqInt bezier, sqInt lineWidth);
static sqInt copyBitsFromtoat(sqInt x0, sqInt x1, sqInt yValue);
static sqInt createGlobalEdgeTable(void);
static sqInt displaySpanBufferAt(sqInt y);
static sqInt fillBitmapSpanAAfromtoat(sqInt bmFill, sqInt leftX, sqInt rightX,
                                      sqInt yValue);
static sqInt fillBitmapSpanfromto(int *bits, sqInt leftX, sqInt rightX);
static sqInt fillBitmapSpanfromtoat(sqInt bmFill, sqInt leftX, sqInt rightX,
                                    sqInt yValue);
static sqInt fillColorSpanAAx0x1(sqInt pixelValue32, sqInt leftX, sqInt rightX);
static sqInt fillLinearGradientAArampdsdsXfromto(sqInt fill, int *ramp,
                                                 sqInt deltaS, sqInt dsX,
                                                 sqInt leftX, sqInt rightX);
static sqInt fillLinearGradientfromtoat(sqInt fill, sqInt leftX, sqInt rightX,
                                        sqInt yValue);
static sqInt fillRadialDecreasingAArampdeltaSTdsXdtXfromto(
    sqInt fill, int *ramp, int *deltaST, sqInt dsX, sqInt dtX, sqInt leftX,
    sqInt rightX);
static sqInt fillRadialGradientfromtoat(sqInt fill, sqInt leftX, sqInt rightX,
                                        sqInt yValue);
static sqInt fillRadialIncreasingAArampdeltaSTdsXdtXfromto(
    sqInt fill, int *ramp, int *deltaST, sqInt dsX, sqInt dtX, sqInt leftX,
    sqInt rightX);
static int fillSortsbefore(sqInt fillEntry1, sqInt fillEntry2);
static sqInt fillSpanfromto(unsigned int fill, sqInt leftX, sqInt rightX);
static sqInt findNextExternalEntryFromGET(void);
static sqInt findNextExternalFillFromAET(void);
static sqInt findNextExternalUpdateFromAET(void);
static sqInt findStackFilldepth(sqInt fillIndex, sqInt depth);
EXPORT(const char *) getModuleName(void);
static sqInt getSortsbefore(sqInt edge1, sqInt edge2);
static sqInt hideFilldepth(sqInt fillIndex, sqInt depth);
static sqInt indexForInsertingIntoAET(sqInt edge);
static sqInt initColorTransform(void);
static sqInt initEdgeTransform(void);
EXPORT(sqInt) initialiseModule(void);
static sqInt initializeGETProcessing(void);
static sqInt insertEdgeIntoAET(sqInt edge);
static sqInt insertToAETbeforeIndex(sqInt edge, sqInt index);
static sqInt isEdge(sqInt edge);
static sqInt isFillOkay(sqInt fill);
static sqInt loadAndSubdivideBezierFromviatoisWide(int *point1, int *point2,
                                                   int *point3, sqInt wideFlag);
static sqInt loadBeziersegmentleftFillrightFilloffset(sqInt bezier, sqInt index,
                                                      sqInt leftFillIndex,
                                                      sqInt rightFillIndex,
                                                      sqInt yOffset);
static sqInt loadBitBltFrom(sqInt bbObj);
static int *loadBitsFrom(sqInt bmFill);
static sqInt
loadCompressedShapeFromIntPointssegmentsleftFillsrightFillslineWidthslineFillsfillIndexList(
    int *points, sqInt nSegments, int *leftFills, int *rightFills,
    int *lineWidths, int *lineFills, int *fillIndexList);
static sqInt
loadCompressedShapeFromShortPointssegmentsleftFillsrightFillslineWidthslineFillsfillIndexList(
    short *points, sqInt nSegments, int *leftFills, int *rightFills,
    int *lineWidths, int *lineFills, int *fillIndexList);
static int loadEdgeStateFrom(sqInt edgeOop);
static sqInt loadEdgeTransformFrom(sqInt transformOop);
static sqInt loadFillOrientationfromalongnormalwidthheight(
    sqInt fill, int *point1, int *point2, int *point3, sqInt fillWidth,
    sqInt fillHeight);
static sqInt loadFormsFrom(sqInt arrayOop);
static sqInt loadGradientFillfromalongnormalisRadial(sqInt rampOop, int *point1,
                                                     int *point2, int *point3,
                                                     sqInt isRadial);
static sqInt loadOvalSegmentwhcxcy(sqInt seg, sqInt w, sqInt h, sqInt cx,
                                   sqInt cy);
static sqInt loadOvallineFillleftFillrightFill(sqInt lineWidth, sqInt lineFill,
                                               sqInt leftFill, sqInt rightFill);
static sqInt loadPointfrom(int *pointArray, sqInt pointOop);
static sqInt loadRenderingState(void);
static sqInt loadShapeFromArraynSegmentsfilllineWidthlineFill(sqInt points,
                                                              sqInt nSegments,
                                                              sqInt fillIndex,
                                                              sqInt lineWidth,
                                                              sqInt lineFill);
static sqInt loadSpanBufferFrom(sqInt spanOop);
static sqInt loadTransformFromArrayintolength(sqInt transformOop,
                                              float *destPtr, sqInt n);
static sqInt loadTransformFromintolength(sqInt transformOop, float *destPtr,
                                         sqInt n);
static sqInt loadWideBezierlineFillleftFillrightFilln(sqInt lineWidth,
                                                      sqInt lineFill,
                                                      sqInt leftFill,
                                                      sqInt rightFill,
                                                      sqInt nSegments);
static sqInt loadWideLinefromtolineFillleftFillrightFill(sqInt lineWidth,
                                                         int *p1, int *p2,
                                                         sqInt lineFill,
                                                         sqInt leftFill,
                                                         sqInt rightFill);
static sqInt loadWorkBufferFrom(sqInt wbOop);
EXPORT(sqInt) moduleUnloaded(char *aModuleName);
static sqInt moveAETEntryFromedgex(sqInt index, sqInt edge, sqInt xValue);
static sqInt postDisplayAction(void);
EXPORT(sqInt) primitiveAbortProcessing(void);
EXPORT(sqInt) primitiveAddActiveEdgeEntry(void);
EXPORT(sqInt) primitiveAddBezier(void);
EXPORT(sqInt) primitiveAddBezierShape(void);
EXPORT(sqInt) primitiveAddBitmapFill(void);
EXPORT(sqInt) primitiveAddCompressedShape(void);
EXPORT(sqInt) primitiveAddGradientFill(void);
EXPORT(sqInt) primitiveAddLine(void);
EXPORT(sqInt) primitiveAddOval(void);
EXPORT(sqInt) primitiveAddPolygon(void);
EXPORT(sqInt) primitiveAddRect(void);
EXPORT(sqInt) primitiveChangedActiveEdgeEntry(void);
EXPORT(sqInt) primitiveCopyBuffer(void);
EXPORT(sqInt) primitiveDisplaySpanBuffer(void);
EXPORT(sqInt) primitiveDoProfileStats(void);
EXPORT(sqInt) primitiveFinishedProcessing(void);
EXPORT(sqInt) primitiveGetAALevel(void);
EXPORT(sqInt) primitiveGetAllStats(void);
EXPORT(sqInt) primitiveGetBezierStats(void);
EXPORT(sqInt) primitiveGetClipRect(void);
EXPORT(sqInt) primitiveGetCounts(void);
EXPORT(sqInt) primitiveGetDepth(void);
EXPORT(sqInt) primitiveGetFailureReason(void);
EXPORT(sqInt) primitiveGetOffset(void);
EXPORT(sqInt) primitiveGetTimes(void);
EXPORT(sqInt) primitiveInitializeBuffer(void);
EXPORT(sqInt) primitiveInitializeProcessing(void);
EXPORT(sqInt) primitiveMergeFillFrom(void);
EXPORT(sqInt) primitiveNeedsFlush(void);
EXPORT(sqInt) primitiveNeedsFlushPut(void);
EXPORT(sqInt) primitiveNextActiveEdgeEntry(void);
EXPORT(sqInt) primitiveNextFillEntry(void);
EXPORT(sqInt) primitiveNextGlobalEdgeEntry(void);
EXPORT(sqInt) primitiveRegisterExternalEdge(void);
EXPORT(sqInt) primitiveRegisterExternalFill(void);
EXPORT(sqInt) primitiveRenderAllScanlines(void);
EXPORT(sqInt) primitiveRenderImage(void);
EXPORT(sqInt) primitiveRenderScanline(void);
EXPORT(sqInt) primitiveSetAALevel(void);
EXPORT(sqInt) primitiveSetBitBltPlugin(void);
EXPORT(sqInt) primitiveSetClipRect(void);
EXPORT(sqInt) primitiveSetColorTransform(void);
EXPORT(sqInt) primitiveSetDepth(void);
EXPORT(sqInt) primitiveSetEdgeTransform(void);
EXPORT(sqInt) primitiveSetOffset(void);
static sqInt proceedRenderingImage(void);
static sqInt proceedRenderingScanline(void);
static sqInt quickLoadEngineFrom(sqInt engineOop);
static sqInt quickLoadEngineFromrequiredState(sqInt oop, sqInt requiredState);
static sqInt quickLoadEngineFromrequiredStateor(sqInt oop, sqInt requiredState,
                                                sqInt alternativeState);
static sqInt quickSortGlobalEdgeTablefromto(int *array, sqInt i, sqInt j);
static sqInt removeFirstAETEntry(void);
static sqInt resetGraphicsEngineStats(void);
static sqInt resortFirstAETEntry(void);
static int *rShiftTable(void);
static sqInt setAALevel(sqInt level);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);
static sqInt showFilldepthrightX(sqInt fillIndex, sqInt depth, sqInt rightX);
static int *smallSqrtTable(void);
static sqInt stepToFirstBezierInat(sqInt bezier, sqInt yValue);
static sqInt stepToFirstLineInat(sqInt line, sqInt yValue);
static sqInt stepToFirstWideBezierInat(sqInt bezier, sqInt yValue);
static sqInt stepToFirstWideLineInat(sqInt line, sqInt yValue);
static sqInt stepToNextWideBezierInat(sqInt bezier, sqInt yValue);
static sqInt storeEdgeStateFrominto(sqInt edge, sqInt edgeOop);
static sqInt storeFillStateInto(sqInt fillOop);
static sqInt storeRenderingState(void);
static sqInt subdivideBezierFrom(sqInt index);
static sqInt subdivideBezier(sqInt index);
static sqInt subdivideToBeMonotonInX(sqInt index);
static sqInt subdivideToBeMonotonInY(sqInt index);
static sqInt subdivideToBeMonotoninX(sqInt base, sqInt doTestX);
static sqInt toggleFillsOf(sqInt edge);
static sqInt toggleFilldepthrightX(sqInt fillIndex, sqInt depth, sqInt rightX);
static sqInt toggleWideFillOf(sqInt edge);
static int topDepth(void);
static int topFill(void);
static int topRightX(void);
static sqInt transformColor(sqInt fillIndex);
static sqInt transformWidth(sqInt w);
static sqInt uncheckedTransformColor(sqInt fillIndex);

/*** Variables ***/
static int *aetBuffer;
static char bbPluginName[256] = "BitBltPlugin";
static void *copyBitsFn;
static sqInt dispatchedValue;
static sqInt dispatchReturnValue;
static sqInt engine;
static sqInt engineStopped;
static sqInt formArray;
static sqInt geProfileTime;
static int *getBuffer;

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*booleanValueOf)(sqInt obj);
static sqInt (*byteSizeOf)(sqInt oop);
static sqInt (*classBitmap)(void);
static sqInt (*classPoint)(void);
static sqInt (*failed)(void);
static sqInt (*fetchClassOf)(sqInt oop);
static sqInt (*fetchIntegerofObject)(sqInt fieldIndex, sqInt objectPointer);
static sqInt (*fetchPointerofObject)(sqInt index, sqInt oop);
static void *(*firstIndexableField)(sqInt oop);
static double (*floatValueOf)(sqInt oop);
#if !defined(integerValueOf)
static sqInt (*integerValueOf)(sqInt oop);
#endif
static void *(*ioLoadFunctionFrom)(char *functionName, char *moduleName);
static unsigned int (*ioMicroMSecs)(void);
static sqInt (*isArray)(sqInt oop);
static sqInt (*isBytes)(sqInt oop);
static sqInt (*isFloatObject)(sqInt oop);
#if !defined(isImmediate)
static sqInt (*isImmediate)(sqInt anObject);
#endif
#if !defined(isIntegerObject)
static sqInt (*isIntegerObject)(sqInt objectPointer);
#endif
static sqInt (*isPointers)(sqInt oop);
static sqInt (*isWords)(sqInt oop);
static sqInt (*makePointwithxValueyValue)(sqInt xValue, sqInt yValue);
static sqInt (*methodArgumentCount)(void);
static sqInt (*methodReturnInteger)(sqInt integer);
static sqInt (*methodReturnReceiver)(void);
static sqInt (*nilObject)(void);
static sqInt (*pop)(sqInt nItems);
static sqInt (*popthenPush)(sqInt nItems, sqInt oop);
static sqInt (*popRemappableOop)(void);
static sqInt (*positive32BitIntegerFor)(unsigned int integerValue);
static usqInt (*positive32BitValueOf)(sqInt oop);
static sqInt (*primitiveFail)(void);
static sqInt (*primitiveFailFor)(sqInt reasonCode);
static sqInt (*pushBool)(sqInt trueOrFalse);
static sqInt (*pushInteger)(sqInt integerValue);
static sqInt (*pushRemappableOop)(sqInt oop);
static sqInt (*slotSizeOf)(sqInt oop);
static sqInt (*stackIntegerValue)(sqInt offset);
static sqInt (*stackObjectValue)(sqInt offset);
static sqInt (*stackValue)(sqInt offset);
static sqInt (*storeIntegerofObjectwithValue)(sqInt index, sqInt oop,
                                              sqInt integer);
static sqInt (*storePointerofObjectwithValue)(sqInt index, sqInt oop,
                                              sqInt valuePointer);
static sqInt (*topRemappableOop)(void);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt booleanValueOf(sqInt obj);
extern sqInt byteSizeOf(sqInt oop);
extern sqInt classBitmap(void);
extern sqInt classPoint(void);
extern sqInt failed(void);
extern sqInt fetchClassOf(sqInt oop);
extern sqInt fetchIntegerofObject(sqInt fieldIndex, sqInt objectPointer);
extern sqInt fetchPointerofObject(sqInt index, sqInt oop);
extern void *firstIndexableField(sqInt oop);
extern double floatValueOf(sqInt oop);
#if !defined(integerValueOf)
extern sqInt integerValueOf(sqInt oop);
#endif
extern void *ioLoadFunctionFrom(char *functionName, char *moduleName);
extern unsigned int ioMicroMSecs(void);
extern sqInt isArray(sqInt oop);
extern sqInt isBytes(sqInt oop);
extern sqInt isFloatObject(sqInt oop);
#if !defined(isImmediate)
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 13)
extern sqInt isImmediate(sqInt anObject);
#else
#define isImmediate(anObject) 0
#endif
#endif /* !defined(isImmediate) */
#if !defined(isIntegerObject)
extern sqInt isIntegerObject(sqInt objectPointer);
#endif
extern sqInt isPointers(sqInt oop);
extern sqInt isWords(sqInt oop);
extern sqInt makePointwithxValueyValue(sqInt xValue, sqInt yValue);
extern sqInt methodArgumentCount(void);
extern sqInt methodReturnInteger(sqInt integer);
extern sqInt methodReturnReceiver(void);
extern sqInt nilObject(void);
extern sqInt pop(sqInt nItems);
extern sqInt popthenPush(sqInt nItems, sqInt oop);
extern sqInt popRemappableOop(void);
extern sqInt positive32BitIntegerFor(unsigned int integerValue);
extern usqInt positive32BitValueOf(sqInt oop);
extern sqInt primitiveFail(void);
extern sqInt primitiveFailFor(sqInt reasonCode);
extern sqInt pushBool(sqInt trueOrFalse);
extern sqInt pushInteger(sqInt integerValue);
extern sqInt pushRemappableOop(sqInt oop);
extern sqInt slotSizeOf(sqInt oop);
extern sqInt stackIntegerValue(sqInt offset);
extern sqInt stackObjectValue(sqInt offset);
extern sqInt stackValue(sqInt offset);
extern sqInt storeIntegerofObjectwithValue(sqInt index, sqInt oop,
                                           sqInt integer);
extern sqInt storePointerofObjectwithValue(sqInt index, sqInt oop,
                                           sqInt valuePointer);
extern sqInt topRemappableOop(void);
extern
#endif
struct VirtualMachine *interpreterProxy;
static void *loadBBFn;
static const char *moduleName = "B2DPlugin VMMaker.oscog-eem.3634 " INT_EXT;
static int *objBuffer;
static sqInt objUsed;
static unsigned int *spanBuffer;
static int *workBuffer;
static int doProfileStats = 0;

/*** Methods ***/

/*	Return the accurate length of the vector described by deltaX and deltaY
 */

/* BalloonEngineBase>>#accurateLengthOf:with: */
#include "functions/accurateLengthOfwith.c"


/* BalloonEngineBase>>#addEdgeToGET: */
#include "functions/addEdgeToGET.c"


/*	Adjust the wide bezier curve (dx < 0) to start/end at the right point */

/* BalloonEnginePlugin>>#adjustWideBezierLeft:width:offset:endX: */
#include "functions/adjustWideBezierLeftwidthoffsetendX.c"


/*	Adjust the wide bezier curve (dx >= 0) to start/end at the right point
 */

/* BalloonEnginePlugin>>#adjustWideBezierRight:width:offset:endX: */
#include "functions/adjustWideBezierRightwidthoffsetendX.c"


/*	Adjust the wide line after it has been stepped from lastX to nextX.
        Special adjustments of line width and start position are made here
        to simulate a rectangular brush */

/* BalloonEnginePlugin>>#adjustWideLine:afterSteppingFrom:to: */
#include "functions/adjustWideLineafterSteppingFromto.c"


/*	Allocate n slots in the global edge table */

/* BalloonEngineBase>>#allocateGETEntry: */
#include "functions/allocateGETEntry.c"


/*	Allocate n slots in the object buffer */

/* BalloonEngineBase>>#allocateObjEntry: */
#include "functions/allocateObjEntry.c"


/*	Check the fill indexes in the run-length encoded fillList */

/* BalloonEnginePlugin>>#checkCompressedFillIndexList:max:segments: */
#include "functions/checkCompressedFillIndexListmaxsegments.c"


/*	Check if the indexList (containing fill handles) is okay. */

/* BalloonEnginePlugin>>#checkCompressedFills: */
#include "functions/checkCompressedFills.c"


/*	Check the run-length encoded lineWidthList matches nSegments */

/* BalloonEnginePlugin>>#checkCompressedLineWidths:segments: */
#include "functions/checkCompressedLineWidthssegments.c"


/*	Check if the given point array can be handled by the engine. */

/* BalloonEnginePlugin>>#checkCompressedPoints:segments: */
#include "functions/checkCompressedPointssegments.c"


/*	Check if the given shape can be handled by the engine.
        Since there are a number of requirements this is an extra method. */

/* BalloonEnginePlugin>>#checkCompressedShape:segments:leftFills:rightFills:lineWidths:lineFills:fillIndexList:
 */
#include "functions/checkCompressedShapesegmentsleftFillsrightFillslineWidthslineFillsfillIndexList.c"


/* BalloonEnginePlugin>>#circleCosTable */
#include "functions/circleCosTable.c"


/* BalloonEnginePlugin>>#circleSinTable */
#include "functions/circleSinTable.c"


/*	Clear the current span buffer.
        The span buffer is only cleared in the area that has been used by the
        previous scan line.
 */

/* BalloonEngineBase>>#clearSpanBuffer */
#include "functions/clearSpanBuffer.c"


/*	Split the bezier curve at 0.5. */

/* BalloonEnginePlugin>>#computeBezierSplitAtHalf: */
#include "functions/computeBezierSplitAtHalf.c"


/*	Split the bezier curve at the given parametric value.
        Note: Since this method is only invoked to make non-monoton
        beziers monoton we must check for the resulting y values
        to be *really* between the start and end value. */

/* BalloonEnginePlugin>>#computeBezier:splitAt: */
#include "functions/computeBeziersplitAt.c"


/*	Get both values from the two boundaries of the given bezier
        and compute the actual position/width of the line */

/* BalloonEnginePlugin>>#computeFinalWideBezierValues:width: */
#include "functions/computeFinalWideBezierValueswidth.c"


/* BalloonEngineBase>>#copyBitsFrom:to:at: */
#include "functions/copyBitsFromtoat.c"


/*	Create the global edge table */

/* BalloonEngineBase>>#createGlobalEdgeTable */
#include "functions/createGlobalEdgeTable.c"


/*	Display the span buffer at the current scan line. */

/* BalloonEngineBase>>#displaySpanBufferAt: */
#include "functions/displaySpanBufferAt.c"


/* BalloonEnginePlugin>>#fillBitmapSpanAA:from:to:at: */
#include "functions/fillBitmapSpanAAfromtoat.c"


/*	Fill the span buffer between leftEdge and rightEdge using the given
   bits. Note: We always start from zero - this avoids using huge bitmap buffers
   if the bitmap is to be displayed at the very far right hand side and also
        gives us a chance of using certain bitmaps (e.g., those with depth 32)
        directly.
 */

/* BalloonEngineBase>>#fillBitmapSpan:from:to: */
#include "functions/fillBitmapSpanfromto.c"


/* BalloonEnginePlugin>>#fillBitmapSpan:from:to:at: */
#include "functions/fillBitmapSpanfromtoat.c"


/*	This is the inner loop for solid color fills with anti-aliasing.
        This loop has been unrolled for speed and quality into three parts:
        a) copy all pixels that fall into the first full pixel.
        b) copy aaLevel pixels between the first and the last full pixel
        c) copy all pixels that fall in the last full pixel */

/* BalloonEngineBase>>#fillColorSpanAA:x0:x1: */
#include "functions/fillColorSpanAAx0x1.c"


/*	This is the AA version of linear gradient filling. */

/* BalloonEnginePlugin>>#fillLinearGradientAA:ramp:ds:dsX:from:to: */
#include "functions/fillLinearGradientAArampdsdsXfromto.c"


/*	Draw a linear gradient fill. */

/* BalloonEnginePlugin>>#fillLinearGradient:from:to:at: */
#include "functions/fillLinearGradientfromtoat.c"


/*	Part 2a) Compute the decreasing part of the ramp */

/* BalloonEnginePlugin>>#fillRadialDecreasingAA:ramp:deltaST:dsX:dtX:from:to: */
#include "functions/fillRadialDecreasingAArampdeltaSTdsXdtXfromto.c"


/*	Draw a radial gradient fill. */

/* BalloonEnginePlugin>>#fillRadialGradient:from:to:at: */
#include "functions/fillRadialGradientfromtoat.c"


/*	Part 2b) Compute the increasing part of the ramp */

/* BalloonEnginePlugin>>#fillRadialIncreasingAA:ramp:deltaST:dsX:dtX:from:to: */
#include "functions/fillRadialIncreasingAArampdeltaSTdsXdtXfromto.c"


/*	Return true if fillEntry1 should be drawn before fillEntry2 */

/* BalloonEngineBase>>#fillSorts:before: */
#include "functions/fillSortsbefore.c"


/*	Fill the span buffer from leftX to rightX with the given fill.
        Clip before performing any operations. Return true if the fill must
        be handled by some Smalltalk code. */

/* BalloonEngineBase>>#fillSpan:from:to: */
#include "functions/fillSpanfromto.c"


/*	Check the global edge table for any entries that cannot be handled by
   the engine itself. If there are any, return true. Otherwise, initialize the
   the edge and add it to the AET
 */

/* BalloonEngineBase>>#findNextExternalEntryFromGET */
#include "functions/findNextExternalEntryFromGET.c"


/*	Scan the active edge table. If there is any fill that cannot be handled
   by the engine itself, return true. Otherwise handle the fills and return
        false.
 */
/*	self currentYGet >= 680 ifTrue:[
        self printAET.
        self halt.
        ].
 */

/* BalloonEngineBase>>#findNextExternalFillFromAET */
#include "functions/findNextExternalFillFromAET.c"


/*	Check the active edge table for any entries that cannot be handled by
   the engine itself. If there are any, return true. Otherwise, step the the
   edge to the next y value.
 */

/* BalloonEngineBase>>#findNextExternalUpdateFromAET */
#include "functions/findNextExternalUpdateFromAET.c"


/* BalloonEngineBase>>#findStackFill:depth: */
#include "functions/findStackFilldepth.c"


/*	Note: This is hardcoded so it can be run from Squeak.
        The module name is used for validating a module *after*
        it is loaded to check if it does really contain the module
        we're thinking it contains. This is important! */

/* InterpreterPlugin>>#getModuleName */
#include "functions/getModuleName.c"


/*	Return true if the edge at index i should sort before the edge at index
 * j. */

/* BalloonEngineBase>>#getSorts:before: */
#include "functions/getSortsbefore.c"


/*	Make the fill style with the given index invisible */

/* BalloonEngineBase>>#hideFill:depth: */
#include "functions/hideFilldepth.c"


/*	Find insertion point for the given edge in the AET */

/* BalloonEngineBase>>#indexForInsertingIntoAET: */
#include "functions/indexForInsertingIntoAET.c"


/* BalloonEngineBase>>#initColorTransform */
#include "functions/initColorTransform.c"


/* BalloonEngineBase>>#initEdgeTransform */
#include "functions/initEdgeTransform.c"


/* BalloonEngineBase>>#initialiseModule */
#include "functions/initialiseModule.c"


/*	Initialization stuff that needs to be done before any processing can
   take place.
 */
/*	Make sure aaLevel is initialized */

/* BalloonEngineBase>>#initializeGETProcessing */
#include "functions/initializeGETProcessing.c"


/*	Insert the edge with the given index from the global edge table into the
        active edge table.
        The edge has already been stepped to the initial yValue -- thus
        remainingLines and rasterX
        are both set.
 */

/* BalloonEngineBase>>#insertEdgeIntoAET: */
#include "functions/insertEdgeIntoAET.c"


/*	Insert the given edge into the AET. */

/* BalloonEngineBase>>#insertToAET:beforeIndex: */
#include "functions/insertToAETbeforeIndex.c"


/* BalloonEngineBase>>#isEdge: */
#include "functions/isEdge.c"


/* BalloonEnginePlugin>>#isFillOkay: */
#include "functions/isFillOkay.c"


/*	Load and subdivide the bezier curve from point1/point2/point3.
        If wideFlag is set then make sure the curve is monoton in X. */

/* BalloonEnginePlugin>>#loadAndSubdivideBezierFrom:via:to:isWide: */
#include "functions/loadAndSubdivideBezierFromviatoisWide.c"


/*	Initialize the bezier segment stored on the stack */

/* BalloonEnginePlugin>>#loadBezier:segment:leftFill:rightFill:offset: */
#include "functions/loadBeziersegmentleftFillrightFilloffset.c"


/* BalloonEngineBase>>#loadBitBltFrom: */
#include "functions/loadBitBltFrom.c"


/*	Note: Assumes that the contents of formArray has been checked before */

/* BalloonEnginePlugin>>#loadBitsFrom: */
#include "functions/loadBitsFrom.c"


/*	Load a compressed shape into the engine.
        WARNING: THIS METHOD NEEDS THE FULL FRAME SIZE!!!!
         */

/* BalloonEnginePlugin>>#loadCompressedShapeFromIntPoints:segments:leftFills:rightFills:lineWidths:lineFills:fillIndexList:
 */
#include "functions/loadCompressedShapeFromIntPointssegmentsleftFillsrightFillslineWidthslineFillsfillIndexList.c"


/*	Load a compressed shape into the engine.
        WARNING: THIS METHOD NEEDS THE FULL FRAME SIZE!!!!
         */

/* BalloonEnginePlugin>>#loadCompressedShapeFromShortPoints:segments:leftFills:rightFills:lineWidths:lineFills:fillIndexList:
 */
#include "functions/loadCompressedShapeFromShortPointssegmentsleftFillsrightFillslineWidthslineFillsfillIndexList.c"


/* BalloonEngineBase>>#loadEdgeStateFrom: */
#include "functions/loadEdgeStateFrom.c"


/*	Load a 2x3 transformation matrix from the given oop.
        Return true if the matrix is not nil, false otherwise */

/* BalloonEngineBase>>#loadEdgeTransformFrom: */
#include "functions/loadEdgeTransformFrom.c"


/*	Transform the points */

/* BalloonEnginePlugin>>#loadFillOrientation:from:along:normal:width:height: */
#include "functions/loadFillOrientationfromalongnormalwidthheight.c"


/*	Check all the forms from arrayOop. */

/* BalloonEngineBase>>#loadFormsFrom: */
#include "functions/loadFormsFrom.c"


/*	Load the gradient fill as defined by the color ramp. */

/* BalloonEnginePlugin>>#loadGradientFill:from:along:normal:isRadial: */
#include "functions/loadGradientFillfromalongnormalisRadial.c"


/* BalloonEnginePlugin>>#loadOvalSegment:w:h:cx:cy: */
#include "functions/loadOvalSegmentwhcxcy.c"


/*	Load a rectangular oval currently defined by point1/point2 */

/* BalloonEnginePlugin>>#loadOval:lineFill:leftFill:rightFill: */
#include "functions/loadOvallineFillleftFillrightFill.c"


/*	Load the contents of pointOop into pointArray */

/* BalloonEngineBase>>#loadPoint:from: */
#include "functions/loadPointfrom.c"


/*	Load the entire state from the interpreter for the rendering primitives.
        Answer 0 on success or a non-zero failure code on failure. */

/* BalloonEngineBase>>#loadRenderingState */
#include "functions/loadRenderingState.c"


/* BalloonEnginePlugin>>#loadShapeFromArray:nSegments:fill:lineWidth:lineFill:
 */
#include "functions/loadShapeFromArraynSegmentsfilllineWidthlineFill.c"


/*	Load the span buffer from the given oop.
        Answer 0 on success or a non-zero failure code on failure. */

/* BalloonEngineBase>>#loadSpanBufferFrom: */
#include "functions/loadSpanBufferFrom.c"


/*	Load a transformation from the given array. */

/* BalloonEngineBase>>#loadTransformFromArray:into:length: */
#include "functions/loadTransformFromArrayintolength.c"


/*	Load a transformation from transformOop into the float array
        defined by destPtr. The transformation is assumed to be either
        an array or a FloatArray of length n. */

/* BalloonEngineBase>>#loadTransformFrom:into:length: */
#include "functions/loadTransformFromintolength.c"


/*	Load the (possibly wide) bezier from the segments currently on the
   bezier stack.
 */

/* BalloonEnginePlugin>>#loadWideBezier:lineFill:leftFill:rightFill:n: */
#include "functions/loadWideBezierlineFillleftFillrightFilln.c"


/*	Load a (possibly wide) line defined by the points p1 and p2 */

/* BalloonEnginePlugin>>#loadWideLine:from:to:lineFill:leftFill:rightFill: */
#include "functions/loadWideLinefromtolineFillleftFillrightFill.c"


/*	Load the working buffer from the given oop */

/* BalloonEngineBase>>#loadWorkBufferFrom: */
#include "functions/loadWorkBufferFrom.c"


/*	The module with the given name was just unloaded.
        Make sure we have no dangling references. */

/* BalloonEngineBase>>#moduleUnloaded: */
#include "functions/moduleUnloaded.c"


/*	The entry at index is not in the right position of the AET.
        Move it to the left until the position is okay. */

/* BalloonEngineBase>>#moveAETEntryFrom:edge:x: */
#include "functions/moveAETEntryFromedgex.c"


/*	We have just blitted a scan line to the screen.
        Do whatever seems to be a good idea here. */
/*	Note: In the future we may check the time needed for this scan line and
        interrupt processing to give the Smalltalk code a chance to run at a
        certain time.
 */
/*	Check if there is any more work to do. */

/* BalloonEngineBase>>#postDisplayAction */
#include "functions/postDisplayAction.c"


/* BalloonEngineBase>>#primitiveAbortProcessing */
#include "functions/primitiveAbortProcessing.c"


/*	Note: No need to load either bitBlt or spanBuffer */

/* BalloonEngineBase>>#primitiveAddActiveEdgeEntry */
#include "functions/primitiveAddActiveEdgeEntry.c"


/*	Fail if we have the wrong number of arguments */

/* BalloonEnginePlugin>>#primitiveAddBezier */
#include "functions/primitiveAddBezier.c"


/*	Fail if we have the wrong number of arguments */

/* BalloonEnginePlugin>>#primitiveAddBezierShape */
#include "functions/primitiveAddBezierShape.c"


/*	Fail if we have the wrong number of arguments */

/* BalloonEnginePlugin>>#primitiveAddBitmapFill */
#include "functions/primitiveAddBitmapFill.c"


/*	Fail if we have the wrong number of arguments */

/* BalloonEnginePlugin>>#primitiveAddCompressedShape */
#include "functions/primitiveAddCompressedShape.c"


/*	Fail if we have the wrong number of arguments */

/* BalloonEnginePlugin>>#primitiveAddGradientFill */
#include "functions/primitiveAddGradientFill.c"


/*	Fail if we have the wrong number of arguments */

/* BalloonEnginePlugin>>#primitiveAddLine */
#include "functions/primitiveAddLine.c"


/*	Fail if we have the wrong number of arguments */

/* BalloonEnginePlugin>>#primitiveAddOval */
#include "functions/primitiveAddOval.c"


/*	Fail if we have the wrong number of arguments */

/* BalloonEnginePlugin>>#primitiveAddPolygon */
#include "functions/primitiveAddPolygon.c"


/*	Fail if we have the wrong number of arguments */

/* BalloonEnginePlugin>>#primitiveAddRect */
#include "functions/primitiveAddRect.c"


/*	Note: No need to load either bitBlt or spanBuffer */

/* BalloonEngineBase>>#primitiveChangedActiveEdgeEntry */
#include "functions/primitiveChangedActiveEdgeEntry.c"


/* BalloonEngineBase>>#primitiveCopyBuffer */
#include "functions/primitiveCopyBuffer.c"


/*	Note: Must load bitBlt and spanBuffer */

/* BalloonEngineBase>>#primitiveDisplaySpanBuffer */
#include "functions/primitiveDisplaySpanBuffer.c"


/*	Turn on/off profiling. Return the old value of the flag. */

/* BalloonEngineBase>>#primitiveDoProfileStats */
#include "functions/primitiveDoProfileStats.c"


/* BalloonEngineBase>>#primitiveFinishedProcessing */
#include "functions/primitiveFinishedProcessing.c"


/* BalloonEngineBase>>#primitiveGetAALevel */
#include "functions/primitiveGetAALevel.c"


/*	A combination of primitiveGetBezierStats, primitiveGetTimes, &
        primitiveGetCounts
 */

/* BalloonEngineBase>>#primitiveGetAllStats */
#include "functions/primitiveGetAllStats.c"


/* BalloonEnginePlugin>>#primitiveGetBezierStats */
#include "functions/primitiveGetBezierStats.c"


/* BalloonEngineBase>>#primitiveGetClipRect */
#include "functions/primitiveGetClipRect.c"


/* BalloonEngineBase>>#primitiveGetCounts */
#include "functions/primitiveGetCounts.c"


/* BalloonEngineBase>>#primitiveGetDepth */
#include "functions/primitiveGetDepth.c"


/*	Return the reason why the last operation failed. */

/* BalloonEngineBase>>#primitiveGetFailureReason */
#include "functions/primitiveGetFailureReason.c"


/* BalloonEngineBase>>#primitiveGetOffset */
#include "functions/primitiveGetOffset.c"


/* BalloonEngineBase>>#primitiveGetTimes */
#include "functions/primitiveGetTimes.c"


/* BalloonEngineBase>>#primitiveInitializeBuffer */
#include "functions/primitiveInitializeBuffer.c"


/*	Note: No need to load bitBlt but must load spanBuffer */

/* BalloonEngineBase>>#primitiveInitializeProcessing */
#include "functions/primitiveInitializeProcessing.c"


/*	Note: No need to load bitBlt but must load spanBuffer */

/* BalloonEngineBase>>#primitiveMergeFillFrom */
#include "functions/primitiveMergeFillFrom.c"


/* BalloonEngineBase>>#primitiveNeedsFlush */
#include "functions/primitiveNeedsFlush.c"


/* BalloonEngineBase>>#primitiveNeedsFlushPut */
#include "functions/primitiveNeedsFlushPut.c"


/*	Note: No need to load either bitBlt or spanBuffer */

/* BalloonEngineBase>>#primitiveNextActiveEdgeEntry */
#include "functions/primitiveNextActiveEdgeEntry.c"


/*	Note: No need to load bitBlt but must load spanBuffer */

/* BalloonEngineBase>>#primitiveNextFillEntry */
#include "functions/primitiveNextFillEntry.c"


/*	Note: No need to load either bitBlt or spanBuffer */

/* BalloonEngineBase>>#primitiveNextGlobalEdgeEntry */
#include "functions/primitiveNextGlobalEdgeEntry.c"


/* BalloonEngineBase>>#primitiveRegisterExternalEdge */
#include "functions/primitiveRegisterExternalEdge.c"


/* BalloonEngineBase>>#primitiveRegisterExternalFill */
#include "functions/primitiveRegisterExternalFill.c"


/*	Condense the trio of
        [self primFinishedProcessing]
        whileFalse:
        [reason := self primRenderScanline: edge with: fill.
        reason = 0 ifFalse:
        [self processStopReason: reason edge: edge fill: fill]]
        into two primitives:
        [(reason := self primRenderAllScanlines: edge with: fill) ~= 0]
   whileTrue: [self processStopReason: reason edge: edge fill: fill]. */

/* BalloonEngineBase>>#primitiveRenderAllScanlines */
#include "functions/primitiveRenderAllScanlines.c"


/*	Start/Proceed rendering the entire image */

/* BalloonEngineBase>>#primitiveRenderImage */
#include "functions/primitiveRenderImage.c"


/*	Start rendering the entire image */

/* BalloonEngineBase>>#primitiveRenderScanline */
#include "functions/primitiveRenderScanline.c"


/* BalloonEngineBase>>#primitiveSetAALevel */
#include "functions/primitiveSetAALevel.c"


/*	Primitive. Set the BitBlt plugin to use. */

/* BalloonEngineBase>>#primitiveSetBitBltPlugin */
#include "functions/primitiveSetBitBltPlugin.c"


/* BalloonEngineBase>>#primitiveSetClipRect */
#include "functions/primitiveSetClipRect.c"


/* BalloonEngineBase>>#primitiveSetColorTransform */
#include "functions/primitiveSetColorTransform.c"


/* BalloonEngineBase>>#primitiveSetDepth */
#include "functions/primitiveSetDepth.c"


/* BalloonEngineBase>>#primitiveSetEdgeTransform */
#include "functions/primitiveSetEdgeTransform.c"


/* BalloonEngineBase>>#primitiveSetOffset */
#include "functions/primitiveSetOffset.c"


/*	This is the main rendering entry */

/* BalloonEngineBase>>#proceedRenderingImage */
#include "functions/proceedRenderingImage.c"


/*	Proceed rendering the current scan line.
        This method may be called after some Smalltalk code has been executed
        inbetween.
 */
/*	This is the main rendering entry */

/* BalloonEngineBase>>#proceedRenderingScanline */
#include "functions/proceedRenderingScanline.c"


/*	Load the minimal required state from the engineOop, e.g., just the work
        buffer. Answer 0 on success or non-zero a failure code on failure */

/* BalloonEngineBase>>#quickLoadEngineFrom: */
#include "functions/quickLoadEngineFrom.c"


/* BalloonEngineBase>>#quickLoadEngineFrom:requiredState: */
#include "functions/quickLoadEngineFromrequiredState.c"


/* BalloonEngineBase>>#quickLoadEngineFrom:requiredState:or: */
#include "functions/quickLoadEngineFromrequiredStateor.c"


/*	Sort elements i through j of self to be nondescending according to
        sortBlock. */
/*	Note: The original loop has been heavily re-written for C translation */

/* BalloonEngineBase>>#quickSortGlobalEdgeTable:from:to: */
#include "functions/quickSortGlobalEdgeTablefromto.c"


/* BalloonEngineBase>>#removeFirstAETEntry */
#include "functions/removeFirstAETEntry.c"


/* BalloonEngineBase>>#resetGraphicsEngineStats */
#include "functions/resetGraphicsEngineStats.c"


/* BalloonEngineBase>>#resortFirstAETEntry */
#include "functions/resortFirstAETEntry.c"


/* BalloonEnginePlugin>>#rShiftTable */
#include "functions/rShiftTable.c"


/*	Set the anti-aliasing level. Three levels are supported:
        1 - No antialiasing
        2 - 2x2 unweighted anti-aliasing
        4 - 4x4 unweighted anti-aliasing.
         */

/* BalloonEngineBase>>#setAALevel: */
#include "functions/setAALevel.c"


/*	Note: This is coded so that it can be run in Squeak. */

/* InterpreterPlugin>>#setInterpreter: */
#include "functions/setInterpreter.c"


/* BalloonEngineBase>>#showFill:depth:rightX: */
#include "functions/showFilldepthrightX.c"


/* BalloonEngineBase>>#smallSqrtTable */
#include "functions/smallSqrtTable.c"


/*	Initialize the bezier at yValue.
        TODO: Check if reducing maxSteps from 2*deltaY to deltaY
        brings a *significant* performance improvement.
        In theory this should make for double step performance
        but will cost in quality. Might be that the AA stuff will
        compensate for this - but I'm not really sure. */

/* BalloonEnginePlugin>>#stepToFirstBezierIn:at: */
#include "functions/stepToFirstBezierInat.c"


/*	Initialize the line at yValue */

/* BalloonEnginePlugin>>#stepToFirstLineIn:at: */
#include "functions/stepToFirstLineInat.c"


/*	Initialize the bezier at yValue */

/* BalloonEnginePlugin>>#stepToFirstWideBezierIn:at: */
#include "functions/stepToFirstWideBezierInat.c"


/*	Initialize the wide line at yValue. */

/* BalloonEnginePlugin>>#stepToFirstWideLineIn:at: */
#include "functions/stepToFirstWideLineInat.c"


/*	Incrementally step to the next scan line in the given wide bezier */

/* BalloonEnginePlugin>>#stepToNextWideBezierIn:at: */
#include "functions/stepToNextWideBezierInat.c"


/* BalloonEngineBase>>#storeEdgeStateFrom:into: */
#include "functions/storeEdgeStateFrominto.c"


/* BalloonEngineBase>>#storeFillStateInto: */
#include "functions/storeFillStateInto.c"


/* BalloonEngineBase>>#storeRenderingState */
#include "functions/storeRenderingState.c"


/*	Recursively subdivide the curve on the bezier stack. */

/* BalloonEnginePlugin>>#subdivideBezierFrom: */
#include "functions/subdivideBezierFrom.c"


/*	Subdivide the given bezier curve if necessary */

/* BalloonEnginePlugin>>#subdivideBezier: */
#include "functions/subdivideBezier.c"


/*	Check if the given bezier curve is monoton in X. If not, subdivide it */

/* BalloonEnginePlugin>>#subdivideToBeMonotonInX: */
#include "functions/subdivideToBeMonotonInX.c"


/*	Check if the given bezier curve is monoton in Y. If not, subdivide it */

/* BalloonEnginePlugin>>#subdivideToBeMonotonInY: */
#include "functions/subdivideToBeMonotonInY.c"


/*	Check if the given bezier curve is monoton in Y, and, if desired in X.
        If not, subdivide it */

/* BalloonEnginePlugin>>#subdivideToBeMonoton:inX: */
#include "functions/subdivideToBeMonotoninX_1.c"


/* BalloonEngineBase>>#toggleFillsOf: */
#include "functions/toggleFillsOf.c"


/*	Make the fill style with the given index either visible or invisible */

/* BalloonEngineBase>>#toggleFill:depth:rightX: */
#include "functions/toggleFilldepthrightX.c"


/* BalloonEngineBase>>#toggleWideFillOf: */
#include "functions/toggleWideFillOf.c"


/* BalloonEngineBase>>#topDepth */
#include "functions/topDepth.c"


/* BalloonEngineBase>>#topFill */
#include "functions/topFill.c"


/* BalloonEngineBase>>#topRightX */
#include "functions/topRightX.c"


/* BalloonEngineBase>>#transformColor: */
#include "functions/transformColor.c"


/*	Transform the given width */

/* BalloonEngineBase>>#transformWidth: */
#include "functions/transformWidth.c"


/* BalloonEngineBase>>#uncheckedTransformColor: */
#include "functions/uncheckedTransformColor.c"


/*** Exports ***/

#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "B2DPlugin";
void *B2DPlugin_exports[][3] = {
    {(void *)_m, "getModuleName", (void *)getModuleName},
    {(void *)_m, "initialiseModule", (void *)initialiseModule},
    {(void *)_m, "moduleUnloaded", (void *)moduleUnloaded},
    {(void *)_m, "primitiveAbortProcessing\000\002\003",
     (void *)primitiveAbortProcessing},
    {(void *)_m, "primitiveAddActiveEdgeEntry\000\002\003",
     (void *)primitiveAddActiveEdgeEntry},
    {(void *)_m, "primitiveAddBezier\000\002\003", (void *)primitiveAddBezier},
    {(void *)_m, "primitiveAddBezierShape\000\002\003",
     (void *)primitiveAddBezierShape},
    {(void *)_m, "primitiveAddBitmapFill\000\002\003",
     (void *)primitiveAddBitmapFill},
    {(void *)_m, "primitiveAddCompressedShape\000\002\003",
     (void *)primitiveAddCompressedShape},
    {(void *)_m, "primitiveAddGradientFill\000\002\003",
     (void *)primitiveAddGradientFill},
    {(void *)_m, "primitiveAddLine\000\002\003", (void *)primitiveAddLine},
    {(void *)_m, "primitiveAddOval\000\002\003", (void *)primitiveAddOval},
    {(void *)_m, "primitiveAddPolygon\000\002\003",
     (void *)primitiveAddPolygon},
    {(void *)_m, "primitiveAddRect\000\002\003", (void *)primitiveAddRect},
    {(void *)_m, "primitiveChangedActiveEdgeEntry\000\002\003",
     (void *)primitiveChangedActiveEdgeEntry},
    {(void *)_m, "primitiveCopyBuffer\000\001\003",
     (void *)primitiveCopyBuffer},
    {(void *)_m, "primitiveDisplaySpanBuffer\000\002\000",
     (void *)primitiveDisplaySpanBuffer},
    {(void *)_m, "primitiveDoProfileStats\000\000\003",
     (void *)primitiveDoProfileStats},
    {(void *)_m, "primitiveFinishedProcessing\000\002\003",
     (void *)primitiveFinishedProcessing},
    {(void *)_m, "primitiveGetAALevel\000\002\003",
     (void *)primitiveGetAALevel},
    {(void *)_m, "primitiveGetAllStats\000\002\003",
     (void *)primitiveGetAllStats},
    {(void *)_m, "primitiveGetBezierStats\000\002\003",
     (void *)primitiveGetBezierStats},
    {(void *)_m, "primitiveGetClipRect\000\002\003",
     (void *)primitiveGetClipRect},
    {(void *)_m, "primitiveGetCounts\000\002\003", (void *)primitiveGetCounts},
    {(void *)_m, "primitiveGetDepth\000\002\003", (void *)primitiveGetDepth},
    {(void *)_m, "primitiveGetFailureReason\000\002\003",
     (void *)primitiveGetFailureReason},
    {(void *)_m, "primitiveGetOffset\000\002\003", (void *)primitiveGetOffset},
    {(void *)_m, "primitiveGetTimes\000\002\003", (void *)primitiveGetTimes},
    {(void *)_m, "primitiveInitializeBuffer\000\001\003",
     (void *)primitiveInitializeBuffer},
    {(void *)_m, "primitiveInitializeProcessing\000\002\003",
     (void *)primitiveInitializeProcessing},
    {(void *)_m, "primitiveMergeFillFrom\000\002\003",
     (void *)primitiveMergeFillFrom},
    {(void *)_m, "primitiveNeedsFlush\000\002\003",
     (void *)primitiveNeedsFlush},
    {(void *)_m, "primitiveNeedsFlushPut\000\002\003",
     (void *)primitiveNeedsFlushPut},
    {(void *)_m, "primitiveNextActiveEdgeEntry\000\002\003",
     (void *)primitiveNextActiveEdgeEntry},
    {(void *)_m, "primitiveNextFillEntry\000\004\003",
     (void *)primitiveNextFillEntry},
    {(void *)_m, "primitiveNextGlobalEdgeEntry\000\002\003",
     (void *)primitiveNextGlobalEdgeEntry},
    {(void *)_m, "primitiveRegisterExternalEdge\000\002\003",
     (void *)primitiveRegisterExternalEdge},
    {(void *)_m, "primitiveRegisterExternalFill\000\002\003",
     (void *)primitiveRegisterExternalFill},
    {(void *)_m, "primitiveRenderAllScanlines\000\377\000",
     (void *)primitiveRenderAllScanlines},
    {(void *)_m, "primitiveRenderImage\000\377\000",
     (void *)primitiveRenderImage},
    {(void *)_m, "primitiveRenderScanline\000\377\000",
     (void *)primitiveRenderScanline},
    {(void *)_m, "primitiveSetAALevel\000\002\003",
     (void *)primitiveSetAALevel},
    {(void *)_m, "primitiveSetBitBltPlugin\000\001\003",
     (void *)primitiveSetBitBltPlugin},
    {(void *)_m, "primitiveSetClipRect\000\002\003",
     (void *)primitiveSetClipRect},
    {(void *)_m, "primitiveSetColorTransform\000\002\003",
     (void *)primitiveSetColorTransform},
    {(void *)_m, "primitiveSetDepth\000\002\003", (void *)primitiveSetDepth},
    {(void *)_m, "primitiveSetEdgeTransform\000\002\003",
     (void *)primitiveSetEdgeTransform},
    {(void *)_m, "primitiveSetOffset\000\002\003", (void *)primitiveSetOffset},
    {(void *)_m, "setInterpreter", (void *)setInterpreter},
    {NULL, NULL, NULL}};

#else // ifdef SQ_BUILTIN_PLUGIN

#if SPURVM
EXPORT(signed short) primitiveAbortProcessingMetadata = 515;
EXPORT(signed short) primitiveAddActiveEdgeEntryMetadata = 515;
EXPORT(signed short) primitiveAddBezierMetadata = 515;
EXPORT(signed short) primitiveAddBezierShapeMetadata = 515;
EXPORT(signed short) primitiveAddBitmapFillMetadata = 515;
EXPORT(signed short) primitiveAddCompressedShapeMetadata = 515;
EXPORT(signed short) primitiveAddGradientFillMetadata = 515;
EXPORT(signed short) primitiveAddLineMetadata = 515;
EXPORT(signed short) primitiveAddOvalMetadata = 515;
EXPORT(signed short) primitiveAddPolygonMetadata = 515;
EXPORT(signed short) primitiveAddRectMetadata = 515;
EXPORT(signed short) primitiveChangedActiveEdgeEntryMetadata = 515;
EXPORT(signed short) primitiveCopyBufferMetadata = 259;
EXPORT(signed short) primitiveDisplaySpanBufferMetadata = 0x200;
EXPORT(signed short) primitiveDoProfileStatsMetadata = 3;
EXPORT(signed short) primitiveFinishedProcessingMetadata = 515;
EXPORT(signed short) primitiveGetAALevelMetadata = 515;
EXPORT(signed short) primitiveGetAllStatsMetadata = 515;
EXPORT(signed short) primitiveGetBezierStatsMetadata = 515;
EXPORT(signed short) primitiveGetClipRectMetadata = 515;
EXPORT(signed short) primitiveGetCountsMetadata = 515;
EXPORT(signed short) primitiveGetDepthMetadata = 515;
EXPORT(signed short) primitiveGetFailureReasonMetadata = 515;
EXPORT(signed short) primitiveGetOffsetMetadata = 515;
EXPORT(signed short) primitiveGetTimesMetadata = 515;
EXPORT(signed short) primitiveInitializeBufferMetadata = 259;
EXPORT(signed short) primitiveInitializeProcessingMetadata = 515;
EXPORT(signed short) primitiveMergeFillFromMetadata = 515;
EXPORT(signed short) primitiveNeedsFlushMetadata = 515;
EXPORT(signed short) primitiveNeedsFlushPutMetadata = 515;
EXPORT(signed short) primitiveNextActiveEdgeEntryMetadata = 515;
EXPORT(signed short) primitiveNextFillEntryMetadata = 1027;
EXPORT(signed short) primitiveNextGlobalEdgeEntryMetadata = 515;
EXPORT(signed short) primitiveRegisterExternalEdgeMetadata = 515;
EXPORT(signed short) primitiveRegisterExternalFillMetadata = 515;
EXPORT(signed short) primitiveSetAALevelMetadata = 515;
EXPORT(signed short) primitiveSetBitBltPluginMetadata = 259;
EXPORT(signed short) primitiveSetClipRectMetadata = 515;
EXPORT(signed short) primitiveSetColorTransformMetadata = 515;
EXPORT(signed short) primitiveSetDepthMetadata = 515;
EXPORT(signed short) primitiveSetEdgeTransformMetadata = 515;
EXPORT(signed short) primitiveSetOffsetMetadata = 515;
#endif // SPURVM

#endif // ifdef SQ_BUILTIN_PLUGIN
