/* Automatically generated by
        VMPluginCodeGenerator VMMaker.oscog-eem.3634 uuid:
   8a640496-a277-4c3e-be09-22770a14fb3c
        (* Compiler-ct.519)
   from
        BalloonEnginePlugin VMMaker.oscog-eem.3634 uuid:
   8a640496-a277-4c3e-be09-22770a14fb3c
 */
#if defined(__clang__) || defined(__GNUC__)
static const char __buildInfo[] __attribute__((unused)) =
    "BalloonEnginePlugin VMMaker.oscog-eem.3634 uuid: "
    "8a640496-a277-4c3e-be09-22770a14fb3c " __DATE__;
#else
static const char __buildInfo[] =
    "BalloonEnginePlugin VMMaker.oscog-eem.3634 uuid: "
    "8a640496-a277-4c3e-be09-22770a14fb3c " __DATE__;
#endif

#include "config.h"
#include "sqMathShim.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"           /* Configuration options */
#include "sqPlatformSpecific.h" /* Platform specific definitions */
#include "sqVirtualMachine.h"   /*  The virtual machine proxy definition */

#include "sqMemoryAccess.h"

#define true 1
#define false 0
#define null 0 /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
#define EXPORT(returnType) static returnType
#define INT_EXT "(i)"
#else
#define INT_EXT "(e)"
#endif

/*** Constants ***/
#define BEBalloonEngineSize 12
#define BEBitBltIndex 2
#define BEFormsIndex 3
#define BESpanIndex 1
#define BEWorkBufferIndex 0
#define ETBalloonEdgeDataSize 6
#define ETIndexIndex 0
#define ETLinesIndex 4
#define ETXValueIndex 1
#define ETYValueIndex 2
#define ETZValueIndex 3
#define FTBalloonFillDataSize 6
#define FTIndexIndex 0
#define FTMaxXIndex 2
#define FTMinXIndex 1
#define FTYValueIndex 3
#define GBBaseSize 16
#define GBBitmapDepth 12
#define GBBitmapHeight 11
#define GBBitmapRaster 14
#define GBBitmapSize 13
#define GBBitmapWidth 10
#define GBColormapOffset 18
#define GBColormapSize 15
#define GBEndX 14
#define GBEndY 15
#define GBFinalX 21
#define GBMBaseSize 18
#define GBTileFlag 16
#define GBUpdateData 10
#define GBUpdateDDX 4
#define GBUpdateDDY 5
#define GBUpdateDX 2
#define GBUpdateDY 3
#define GBUpdateX 0
#define GBUpdateY 1
#define GBViaX 12
#define GBViaY 13
#define GBWideEntry 18
#define GBWideExit 19
#define GBWideExtent 20
#define GBWideFill 16
#define GBWideSize 28
#define GBWideUpdateData 22
#define GBWideWidth 17
#define GEBaseEdgeSize 10
#define GEBaseFillSize 4
#define GEEdgeFillsInvalid 0x10000
#define GEFAlreadyFailed 100
#define GEFBadPoint 121
#define GEFBitBltLoadFailed 122
#define GEFClassMismatch 114
#define GEFEdgeDataTooSmall 112
#define GEFEngineIsInteger 101
#define GEFEngineIsWords 102
#define GEFEngineStopped 104
#define GEFEngineTooSmall 103
#define GEFEntityCheckFailed 120
#define GEFEntityLoadFailed 119
#define GEFFillDataTooSmall 113
#define GEFFormLoadFailed 123
#define GEFillIndexLeft 8
#define GEFillIndexRight 9
#define GEFSizeMismatch 115
#define GEFWorkBufferBadMagic 108
#define GEFWorkBufferIsInteger 105
#define GEFWorkBufferIsPointers 106
#define GEFWorkBufferStartWrong 110
#define GEFWorkBufferTooSmall 107
#define GEFWorkBufferWrongSize 109
#define GEFWorkTooBig 111
#define GEFWrongEdge 118
#define GEFWrongFill 117
#define GEFWrongState 116
#define GENumLines 7
#define GEObjectIndex 2
#define GEObjectLength 1
#define GEObjectType 0
#define GEPrimitiveBezier 6
#define GEPrimitiveClippedBitmapFill 0x400
#define GEPrimitiveEdge 2
#define GEPrimitiveEdgeMask 0xFF
#define GEPrimitiveFill 0x100
#define GEPrimitiveFillMask 0xFF00
#define GEPrimitiveLine 4
#define GEPrimitiveLinearGradientFill 0x200
#define GEPrimitiveRadialGradientFill 0x300
#define GEPrimitiveTypeMask 0xFFFF
#define GEPrimitiveWide 1
#define GEPrimitiveWideBezier 7
#define GEPrimitiveWideLine 5
#define GEPrimitiveWideMask 0xFE
#define GErrorAETEntry 6
#define GErrorBadState 2
#define GErrorFillEntry 5
#define GErrorGETEntry 4
#define GErrorNeedFlush 3
#define GErrorNoMoreSpace 1
#define GEStateAddingFromGET 1
#define GEStateBlitBuffer 5
#define GEStateCompleted 8
#define GEStateScanningAET 3
#define GEStateUnlocked 0
#define GEStateUpdateEdges 6
#define GEStateWaitingChange 7
#define GEStateWaitingForEdge 2
#define GEStateWaitingForFill 4
#define GEXValue 4
#define GEYValue 5
#define GEZValue 6
#define GFDirectionX 6
#define GFDirectionY 7
#define GFNormalX 8
#define GFNormalY 9
#define GFOriginX 4
#define GFOriginY 5
#define GFRampLength 10
#define GFRampOffset 12
#define GGBaseSize 12
#define GLBaseSize 16
#define GLEndX 14
#define GLEndY 15
#define GLError 13
#define GLErrorAdjDown 15
#define GLErrorAdjUp 14
#define GLWideEntry 18
#define GLWideExit 19
#define GLWideExtent 20
#define GLWideFill 16
#define GLWideSize 21
#define GLWideWidth 17
#define GLXDirection 10
#define GLXIncrement 12
#define GLYDirection 11
#define GWAAColorMask 0x33
#define GWAAColorShift 50
#define GWAAHalfPixel 53
#define GWAALevel 48
#define GWAAScanMask 0x34
#define GWAAShift 49
#define GWAETStart 13
#define GWAETUsed 14
#define GWBezierHeightSubdivisions 109
#define GWBezierLineConversions 111
#define GWBezierMonotonSubdivisions 108
#define GWBezierOverflowSubdivisions 110
#define GWBufferTop 10
#define GWClearSpanBuffer 69
#define GWClipMaxX 43
#define GWClipMaxY 45
#define GWClipMinX 42
#define GWClipMinY 44
#define GWColorTransform 24
#define GWCountAddAETEntry 97
#define GWCountChangeAETEntry 107
#define GWCountDisplaySpan 103
#define GWCountFinishTest 93
#define GWCountInitializing 91
#define GWCountMergeFill 101
#define GWCountNextAETEntry 105
#define GWCountNextFillEntry 99
#define GWCountNextGETEntry 95
#define GWCurrentY 88
#define GWCurrentZ 113
#define GWDestOffsetX 46
#define GWDestOffsetY 47
#define GWEdgeTransform 18
#define GWFillMaxX 37
#define GWFillMaxY 39
#define GWFillMinX 36
#define GWFillMinY 38
#define GWGETStart 11
#define GWGETUsed 12
#define GWHasColorTransform 17
#define GWHasEdgeTransform 16
#define GWHeaderSize 128
#define GWLastExportedEdge 65
#define GWLastExportedFill 66
#define GWLastExportedLeftX 67
#define GWLastExportedRightX 68
#define GWMagicIndex 0
#define GWMagicNumber 1097753705
#define GWMinimalSize 256
#define GWNeedsFlush 63
#define GWObjStart 8
#define GWObjUsed 9
#define GWPoint1 80
#define GWPoint2 82
#define GWPoint3 84
#define GWPoint4 86
#define GWSize 1
#define GWSpanEnd 34
#define GWSpanEndAA 35
#define GWSpanSize 33
#define GWSpanStart 32
#define GWState 2
#define GWStopReason 64
#define GWTimeAddAETEntry 96
#define GWTimeChangeAETEntry 106
#define GWTimeDisplaySpan 102
#define GWTimeFinishTest 92
#define GWTimeInitializing 90
#define GWTimeMergeFill 100
#define GWTimeNextAETEntry 104
#define GWTimeNextFillEntry 98
#define GWTimeNextGETEntry 94

/*** Function Prototypes ***/
static sqInt accurateLengthOfwith(sqInt deltaX, sqInt deltaY);
static sqInt addEdgeToGET(sqInt edge);
static sqInt adjustWideBezierLeftwidthoffsetendX(sqInt bezier, sqInt lineWidth,
                                                 sqInt lineOffset, sqInt endX);
static sqInt adjustWideBezierRightwidthoffsetendX(sqInt bezier, sqInt lineWidth,
                                                  sqInt lineOffset, sqInt endX);
static sqInt adjustWideLineafterSteppingFromto(sqInt line, sqInt lastX,
                                               sqInt nextX);
static sqInt allocateGETEntry(sqInt nSlots);
static sqInt allocateObjEntry(sqInt nSlots);
static sqInt checkCompressedFillIndexListmaxsegments(sqInt fillList,
                                                     sqInt maxIndex,
                                                     sqInt nSegs);
static sqInt checkCompressedFills(sqInt indexList);
static int checkCompressedLineWidthssegments(sqInt lineWidthList,
                                             sqInt nSegments);
static sqInt checkCompressedPointssegments(sqInt points, sqInt nSegments);
static sqInt
checkCompressedShapesegmentsleftFillsrightFillslineWidthslineFillsfillIndexList(
    sqInt points, sqInt nSegments, sqInt leftFills, sqInt rightFills,
    sqInt lineWidths, sqInt lineFills, sqInt fillIndexList);
static double *circleCosTable(void);
static double *circleSinTable(void);
static sqInt clearSpanBuffer(void);
static int computeBezierSplitAtHalf(sqInt index);
static int computeBeziersplitAt(sqInt index, double param);
static sqInt computeFinalWideBezierValueswidth(sqInt bezier, sqInt lineWidth);
static sqInt copyBitsFromtoat(sqInt x0, sqInt x1, sqInt yValue);
static sqInt createGlobalEdgeTable(void);
static sqInt displaySpanBufferAt(sqInt y);
static sqInt fillBitmapSpanAAfromtoat(sqInt bmFill, sqInt leftX, sqInt rightX,
                                      sqInt yValue);
static sqInt fillBitmapSpanfromto(int *bits, sqInt leftX, sqInt rightX);
static sqInt fillBitmapSpanfromtoat(sqInt bmFill, sqInt leftX, sqInt rightX,
                                    sqInt yValue);
static sqInt fillColorSpanAAx0x1(sqInt pixelValue32, sqInt leftX, sqInt rightX);
static sqInt fillLinearGradientAArampdsdsXfromto(sqInt fill, int *ramp,
                                                 sqInt deltaS, sqInt dsX,
                                                 sqInt leftX, sqInt rightX);
static sqInt fillLinearGradientfromtoat(sqInt fill, sqInt leftX, sqInt rightX,
                                        sqInt yValue);
static sqInt fillRadialDecreasingAArampdeltaSTdsXdtXfromto(
    sqInt fill, int *ramp, int *deltaST, sqInt dsX, sqInt dtX, sqInt leftX,
    sqInt rightX);
static sqInt fillRadialGradientfromtoat(sqInt fill, sqInt leftX, sqInt rightX,
                                        sqInt yValue);
static sqInt fillRadialIncreasingAArampdeltaSTdsXdtXfromto(
    sqInt fill, int *ramp, int *deltaST, sqInt dsX, sqInt dtX, sqInt leftX,
    sqInt rightX);
static int fillSortsbefore(sqInt fillEntry1, sqInt fillEntry2);
static sqInt fillSpanfromto(unsigned int fill, sqInt leftX, sqInt rightX);
static sqInt findNextExternalEntryFromGET(void);
static sqInt findNextExternalFillFromAET(void);
static sqInt findNextExternalUpdateFromAET(void);
static sqInt findStackFilldepth(sqInt fillIndex, sqInt depth);
EXPORT(const char *) getModuleName(void);
static sqInt getSortsbefore(sqInt edge1, sqInt edge2);
static sqInt hideFilldepth(sqInt fillIndex, sqInt depth);
static sqInt indexForInsertingIntoAET(sqInt edge);
static sqInt initColorTransform(void);
static sqInt initEdgeTransform(void);
EXPORT(sqInt) initialiseModule(void);
static sqInt initializeGETProcessing(void);
static sqInt insertEdgeIntoAET(sqInt edge);
static sqInt insertToAETbeforeIndex(sqInt edge, sqInt index);
static sqInt isEdge(sqInt edge);
static sqInt isFillOkay(sqInt fill);
static sqInt loadAndSubdivideBezierFromviatoisWide(int *point1, int *point2,
                                                   int *point3, sqInt wideFlag);
static sqInt loadBeziersegmentleftFillrightFilloffset(sqInt bezier, sqInt index,
                                                      sqInt leftFillIndex,
                                                      sqInt rightFillIndex,
                                                      sqInt yOffset);
static sqInt loadBitBltFrom(sqInt bbObj);
static int *loadBitsFrom(sqInt bmFill);
static sqInt
loadCompressedShapeFromIntPointssegmentsleftFillsrightFillslineWidthslineFillsfillIndexList(
    int *points, sqInt nSegments, int *leftFills, int *rightFills,
    int *lineWidths, int *lineFills, int *fillIndexList);
static sqInt
loadCompressedShapeFromShortPointssegmentsleftFillsrightFillslineWidthslineFillsfillIndexList(
    short *points, sqInt nSegments, int *leftFills, int *rightFills,
    int *lineWidths, int *lineFills, int *fillIndexList);
static int loadEdgeStateFrom(sqInt edgeOop);
static sqInt loadEdgeTransformFrom(sqInt transformOop);
static sqInt loadFillOrientationfromalongnormalwidthheight(
    sqInt fill, int *point1, int *point2, int *point3, sqInt fillWidth,
    sqInt fillHeight);
static sqInt loadFormsFrom(sqInt arrayOop);
static sqInt loadGradientFillfromalongnormalisRadial(sqInt rampOop, int *point1,
                                                     int *point2, int *point3,
                                                     sqInt isRadial);
static sqInt loadOvalSegmentwhcxcy(sqInt seg, sqInt w, sqInt h, sqInt cx,
                                   sqInt cy);
static sqInt loadOvallineFillleftFillrightFill(sqInt lineWidth, sqInt lineFill,
                                               sqInt leftFill, sqInt rightFill);
static sqInt loadPointfrom(int *pointArray, sqInt pointOop);
static sqInt loadRenderingState(void);
static sqInt loadShapeFromArraynSegmentsfilllineWidthlineFill(sqInt points,
                                                              sqInt nSegments,
                                                              sqInt fillIndex,
                                                              sqInt lineWidth,
                                                              sqInt lineFill);
static sqInt loadSpanBufferFrom(sqInt spanOop);
static sqInt loadTransformFromArrayintolength(sqInt transformOop,
                                              float *destPtr, sqInt n);
static sqInt loadTransformFromintolength(sqInt transformOop, float *destPtr,
                                         sqInt n);
static sqInt loadWideBezierlineFillleftFillrightFilln(sqInt lineWidth,
                                                      sqInt lineFill,
                                                      sqInt leftFill,
                                                      sqInt rightFill,
                                                      sqInt nSegments);
static sqInt loadWideLinefromtolineFillleftFillrightFill(sqInt lineWidth,
                                                         int *p1, int *p2,
                                                         sqInt lineFill,
                                                         sqInt leftFill,
                                                         sqInt rightFill);
static sqInt loadWorkBufferFrom(sqInt wbOop);
EXPORT(sqInt) moduleUnloaded(char *aModuleName);
static sqInt moveAETEntryFromedgex(sqInt index, sqInt edge, sqInt xValue);
static sqInt postDisplayAction(void);
EXPORT(sqInt) primitiveAbortProcessing(void);
EXPORT(sqInt) primitiveAddActiveEdgeEntry(void);
EXPORT(sqInt) primitiveAddBezier(void);
EXPORT(sqInt) primitiveAddBezierShape(void);
EXPORT(sqInt) primitiveAddBitmapFill(void);
EXPORT(sqInt) primitiveAddCompressedShape(void);
EXPORT(sqInt) primitiveAddGradientFill(void);
EXPORT(sqInt) primitiveAddLine(void);
EXPORT(sqInt) primitiveAddOval(void);
EXPORT(sqInt) primitiveAddPolygon(void);
EXPORT(sqInt) primitiveAddRect(void);
EXPORT(sqInt) primitiveChangedActiveEdgeEntry(void);
EXPORT(sqInt) primitiveCopyBuffer(void);
EXPORT(sqInt) primitiveDisplaySpanBuffer(void);
EXPORT(sqInt) primitiveDoProfileStats(void);
EXPORT(sqInt) primitiveFinishedProcessing(void);
EXPORT(sqInt) primitiveGetAALevel(void);
EXPORT(sqInt) primitiveGetAllStats(void);
EXPORT(sqInt) primitiveGetBezierStats(void);
EXPORT(sqInt) primitiveGetClipRect(void);
EXPORT(sqInt) primitiveGetCounts(void);
EXPORT(sqInt) primitiveGetDepth(void);
EXPORT(sqInt) primitiveGetFailureReason(void);
EXPORT(sqInt) primitiveGetOffset(void);
EXPORT(sqInt) primitiveGetTimes(void);
EXPORT(sqInt) primitiveInitializeBuffer(void);
EXPORT(sqInt) primitiveInitializeProcessing(void);
EXPORT(sqInt) primitiveMergeFillFrom(void);
EXPORT(sqInt) primitiveNeedsFlush(void);
EXPORT(sqInt) primitiveNeedsFlushPut(void);
EXPORT(sqInt) primitiveNextActiveEdgeEntry(void);
EXPORT(sqInt) primitiveNextFillEntry(void);
EXPORT(sqInt) primitiveNextGlobalEdgeEntry(void);
EXPORT(sqInt) primitiveRegisterExternalEdge(void);
EXPORT(sqInt) primitiveRegisterExternalFill(void);
EXPORT(sqInt) primitiveRenderAllScanlines(void);
EXPORT(sqInt) primitiveRenderImage(void);
EXPORT(sqInt) primitiveRenderScanline(void);
EXPORT(sqInt) primitiveSetAALevel(void);
EXPORT(sqInt) primitiveSetBitBltPlugin(void);
EXPORT(sqInt) primitiveSetClipRect(void);
EXPORT(sqInt) primitiveSetColorTransform(void);
EXPORT(sqInt) primitiveSetDepth(void);
EXPORT(sqInt) primitiveSetEdgeTransform(void);
EXPORT(sqInt) primitiveSetOffset(void);
static sqInt proceedRenderingImage(void);
static sqInt proceedRenderingScanline(void);
static sqInt quickLoadEngineFrom(sqInt engineOop);
static sqInt quickLoadEngineFromrequiredState(sqInt oop, sqInt requiredState);
static sqInt quickLoadEngineFromrequiredStateor(sqInt oop, sqInt requiredState,
                                                sqInt alternativeState);
static sqInt quickSortGlobalEdgeTablefromto(int *array, sqInt i, sqInt j);
static sqInt removeFirstAETEntry(void);
static sqInt resetGraphicsEngineStats(void);
static sqInt resortFirstAETEntry(void);
static int *rShiftTable(void);
static sqInt setAALevel(sqInt level);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);
static sqInt showFilldepthrightX(sqInt fillIndex, sqInt depth, sqInt rightX);
static int *smallSqrtTable(void);
static sqInt stepToFirstBezierInat(sqInt bezier, sqInt yValue);
static sqInt stepToFirstLineInat(sqInt line, sqInt yValue);
static sqInt stepToFirstWideBezierInat(sqInt bezier, sqInt yValue);
static sqInt stepToFirstWideLineInat(sqInt line, sqInt yValue);
static sqInt stepToNextWideBezierInat(sqInt bezier, sqInt yValue);
static sqInt storeEdgeStateFrominto(sqInt edge, sqInt edgeOop);
static sqInt storeFillStateInto(sqInt fillOop);
static sqInt storeRenderingState(void);
static sqInt subdivideBezierFrom(sqInt index);
static sqInt subdivideBezier(sqInt index);
static sqInt subdivideToBeMonotonInX(sqInt index);
static sqInt subdivideToBeMonotonInY(sqInt index);
static sqInt subdivideToBeMonotoninX(sqInt base, sqInt doTestX);
static sqInt toggleFillsOf(sqInt edge);
static sqInt toggleFilldepthrightX(sqInt fillIndex, sqInt depth, sqInt rightX);
static sqInt toggleWideFillOf(sqInt edge);
static int topDepth(void);
static int topFill(void);
static int topRightX(void);
static sqInt transformColor(sqInt fillIndex);
static sqInt transformWidth(sqInt w);
static sqInt uncheckedTransformColor(sqInt fillIndex);

/*** Variables ***/
static int *aetBuffer;
static char bbPluginName[256] = "BitBltPlugin";
static void *copyBitsFn;
static sqInt dispatchedValue;
static sqInt dispatchReturnValue;
static sqInt engine;
static sqInt engineStopped;
static sqInt formArray;
static sqInt geProfileTime;
static int *getBuffer;

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*booleanValueOf)(sqInt obj);
static sqInt (*byteSizeOf)(sqInt oop);
static sqInt (*classBitmap)(void);
static sqInt (*classPoint)(void);
static sqInt (*failed)(void);
static sqInt (*fetchClassOf)(sqInt oop);
static sqInt (*fetchIntegerofObject)(sqInt fieldIndex, sqInt objectPointer);
static sqInt (*fetchPointerofObject)(sqInt index, sqInt oop);
static void *(*firstIndexableField)(sqInt oop);
static double (*floatValueOf)(sqInt oop);
#if !defined(integerValueOf)
static sqInt (*integerValueOf)(sqInt oop);
#endif
static void *(*ioLoadFunctionFrom)(char *functionName, char *moduleName);
static unsigned int (*ioMicroMSecs)(void);
static sqInt (*isArray)(sqInt oop);
static sqInt (*isBytes)(sqInt oop);
static sqInt (*isFloatObject)(sqInt oop);
#if !defined(isImmediate)
static sqInt (*isImmediate)(sqInt anObject);
#endif
#if !defined(isIntegerObject)
static sqInt (*isIntegerObject)(sqInt objectPointer);
#endif
static sqInt (*isPointers)(sqInt oop);
static sqInt (*isWords)(sqInt oop);
static sqInt (*makePointwithxValueyValue)(sqInt xValue, sqInt yValue);
static sqInt (*methodArgumentCount)(void);
static sqInt (*methodReturnInteger)(sqInt integer);
static sqInt (*methodReturnReceiver)(void);
static sqInt (*nilObject)(void);
static sqInt (*pop)(sqInt nItems);
static sqInt (*popthenPush)(sqInt nItems, sqInt oop);
static sqInt (*popRemappableOop)(void);
static sqInt (*positive32BitIntegerFor)(unsigned int integerValue);
static usqInt (*positive32BitValueOf)(sqInt oop);
static sqInt (*primitiveFail)(void);
static sqInt (*primitiveFailFor)(sqInt reasonCode);
static sqInt (*pushBool)(sqInt trueOrFalse);
static sqInt (*pushInteger)(sqInt integerValue);
static sqInt (*pushRemappableOop)(sqInt oop);
static sqInt (*slotSizeOf)(sqInt oop);
static sqInt (*stackIntegerValue)(sqInt offset);
static sqInt (*stackObjectValue)(sqInt offset);
static sqInt (*stackValue)(sqInt offset);
static sqInt (*storeIntegerofObjectwithValue)(sqInt index, sqInt oop,
                                              sqInt integer);
static sqInt (*storePointerofObjectwithValue)(sqInt index, sqInt oop,
                                              sqInt valuePointer);
static sqInt (*topRemappableOop)(void);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt booleanValueOf(sqInt obj);
extern sqInt byteSizeOf(sqInt oop);
extern sqInt classBitmap(void);
extern sqInt classPoint(void);
extern sqInt failed(void);
extern sqInt fetchClassOf(sqInt oop);
extern sqInt fetchIntegerofObject(sqInt fieldIndex, sqInt objectPointer);
extern sqInt fetchPointerofObject(sqInt index, sqInt oop);
extern void *firstIndexableField(sqInt oop);
extern double floatValueOf(sqInt oop);
#if !defined(integerValueOf)
extern sqInt integerValueOf(sqInt oop);
#endif
extern void *ioLoadFunctionFrom(char *functionName, char *moduleName);
extern unsigned int ioMicroMSecs(void);
extern sqInt isArray(sqInt oop);
extern sqInt isBytes(sqInt oop);
extern sqInt isFloatObject(sqInt oop);
#if !defined(isImmediate)
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 13)
extern sqInt isImmediate(sqInt anObject);
#else
#define isImmediate(anObject) 0
#endif
#endif /* !defined(isImmediate) */
#if !defined(isIntegerObject)
extern sqInt isIntegerObject(sqInt objectPointer);
#endif
extern sqInt isPointers(sqInt oop);
extern sqInt isWords(sqInt oop);
extern sqInt makePointwithxValueyValue(sqInt xValue, sqInt yValue);
extern sqInt methodArgumentCount(void);
extern sqInt methodReturnInteger(sqInt integer);
extern sqInt methodReturnReceiver(void);
extern sqInt nilObject(void);
extern sqInt pop(sqInt nItems);
extern sqInt popthenPush(sqInt nItems, sqInt oop);
extern sqInt popRemappableOop(void);
extern sqInt positive32BitIntegerFor(unsigned int integerValue);
extern usqInt positive32BitValueOf(sqInt oop);
extern sqInt primitiveFail(void);
extern sqInt primitiveFailFor(sqInt reasonCode);
extern sqInt pushBool(sqInt trueOrFalse);
extern sqInt pushInteger(sqInt integerValue);
extern sqInt pushRemappableOop(sqInt oop);
extern sqInt slotSizeOf(sqInt oop);
extern sqInt stackIntegerValue(sqInt offset);
extern sqInt stackObjectValue(sqInt offset);
extern sqInt stackValue(sqInt offset);
extern sqInt storeIntegerofObjectwithValue(sqInt index, sqInt oop,
                                           sqInt integer);
extern sqInt storePointerofObjectwithValue(sqInt index, sqInt oop,
                                           sqInt valuePointer);
extern sqInt topRemappableOop(void);
extern
#endif
struct VirtualMachine *interpreterProxy;
static void *loadBBFn;
static const char *moduleName = "B2DPlugin VMMaker.oscog-eem.3634 " INT_EXT;
static int *objBuffer;
static sqInt objUsed;
static unsigned int *spanBuffer;
static int *workBuffer;
static int doProfileStats = 0;


/* Utility Functions */
#include "functions/utils/accurateLengthOfwith.c"
#include "functions/utils/allocateObjEntry.c"
#include "functions/utils/copyBitsFromtoat.c"
#include "functions/utils/getModuleName.c"
#include "functions/utils/initialiseModule.c"
#include "functions/utils/moduleUnloaded.c"
#include "functions/utils/postDisplayAction.c"
#include "functions/utils/proceedRenderingImage.c"
#include "functions/utils/proceedRenderingScanline.c"
#include "functions/utils/quickLoadEngineFrom.c"
#include "functions/utils/quickLoadEngineFromrequiredState.c"
#include "functions/utils/quickLoadEngineFromrequiredStateor.c"
#include "functions/utils/resetGraphicsEngineStats.c"
#include "functions/utils/setAALevel.c"
#include "functions/utils/setInterpreter.c"
#include "functions/utils/topDepth.c"
#include "functions/utils/topRightX.c"

/* Lookup Tables */
#include "functions/tables/circleCosTable.c"
#include "functions/tables/circleSinTable.c"
#include "functions/tables/rShiftTable.c"
#include "functions/tables/smallSqrtTable.c"

/* Transform Operations */
#include "functions/transforms/initColorTransform.c"
#include "functions/transforms/initEdgeTransform.c"
#include "functions/transforms/transformColor.c"
#include "functions/transforms/transformWidth.c"
#include "functions/transforms/uncheckedTransformColor.c"

/* Validation Functions */
#include "functions/validation/checkCompressedFillIndexListmaxsegments.c"
#include "functions/validation/checkCompressedFills.c"
#include "functions/validation/checkCompressedLineWidthssegments.c"
#include "functions/validation/checkCompressedPointssegments.c"
#include "functions/validation/checkCompressedShapesegmentsleftFillsrightFillslineWidthslineFillsfillIndexList.c"

/* Loaders - Shapes */
#include "functions/loaders/shapes/loadCompressedShapeFromIntPointssegmentsleftFillsrightFillslineWidthslineFillsfillIndexList.c"
#include "functions/loaders/shapes/loadCompressedShapeFromShortPointssegmentsleftFillsrightFillslineWidthslineFillsfillIndexList.c"
#include "functions/loaders/shapes/loadShapeFromArraynSegmentsfilllineWidthlineFill.c"

/* Loaders - State */
#include "functions/loaders/state/loadBitBltFrom.c"
#include "functions/loaders/state/loadBitsFrom.c"
#include "functions/loaders/state/loadFormsFrom.c"
#include "functions/loaders/state/loadRenderingState.c"
#include "functions/loaders/state/loadWorkBufferFrom.c"
#include "functions/loaders/state/storeRenderingState.c"

/* Loaders - Geometry */
#include "functions/loaders/geometry/loadOvallineFillleftFillrightFill.c"
#include "functions/loaders/geometry/loadOvalSegmentwhcxcy.c"
#include "functions/loaders/geometry/loadPointfrom.c"

/* Loaders - Transforms */
#include "functions/loaders/transforms/loadEdgeTransformFrom.c"
#include "functions/loaders/transforms/loadTransformFromArrayintolength.c"
#include "functions/loaders/transforms/loadTransformFromintolength.c"

/* Loaders - Fills */
#include "functions/loaders/loadFillOrientationfromalongnormalwidthheight.c"
#include "functions/loaders/loadGradientFillfromalongnormalisRadial.c"

/* Edge Table - AET (Active Edge Table) */
#include "functions/edges/aet/findNextExternalUpdateFromAET.c"
#include "functions/edges/aet/indexForInsertingIntoAET.c"
#include "functions/edges/aet/insertEdgeIntoAET.c"
#include "functions/edges/aet/insertToAETbeforeIndex.c"
#include "functions/edges/aet/moveAETEntryFromedgex.c"
#include "functions/edges/aet/removeFirstAETEntry.c"
#include "functions/edges/aet/resortFirstAETEntry.c"

/* Edge Table - GET (Global Edge Table) */
#include "functions/edges/get/addEdgeToGET.c"
#include "functions/edges/get/allocateGETEntry.c"
#include "functions/edges/get/createGlobalEdgeTable.c"
#include "functions/edges/get/findNextExternalEntryFromGET.c"
#include "functions/edges/get/initializeGETProcessing.c"

/* Edge Table - Sorting */
#include "functions/edges/sort/getSortsbefore.c"
#include "functions/edges/sort/quickSortGlobalEdgeTablefromto.c"

/* Edge Table - Core */
#include "functions/edges/isEdge.c"
#include "functions/edges/loadEdgeStateFrom.c"
#include "functions/edges/storeEdgeStateFrominto.c"

/* Fill Operations - Color */
#include "functions/fills/color/fillColorSpanAAx0x1.c"
#include "functions/fills/color/fillSpanfromto.c"

/* Fill Operations - Bitmap */
#include "functions/fills/bitmap/fillBitmapSpanAAfromtoat.c"
#include "functions/fills/bitmap/fillBitmapSpanfromto.c"
#include "functions/fills/bitmap/fillBitmapSpanfromtoat.c"

/* Fill Operations - Gradient */
#include "functions/fills/gradient/fillLinearGradientAArampdsdsXfromto.c"
#include "functions/fills/gradient/fillLinearGradientfromtoat.c"
#include "functions/fills/gradient/fillRadialDecreasingAArampdeltaSTdsXdtXfromto.c"
#include "functions/fills/gradient/fillRadialGradientfromtoat.c"
#include "functions/fills/gradient/fillRadialIncreasingAArampdeltaSTdsXdtXfromto.c"

/* Fill Operations - Management */
#include "functions/fills/management/fillSortsbefore.c"
#include "functions/fills/management/findNextExternalFillFromAET.c"
#include "functions/fills/management/findStackFilldepth.c"
#include "functions/fills/management/hideFilldepth.c"
#include "functions/fills/management/isFillOkay.c"
#include "functions/fills/management/showFilldepthrightX.c"
#include "functions/fills/management/storeFillStateInto.c"
#include "functions/fills/management/toggleFilldepthrightX.c"
#include "functions/fills/management/toggleFillsOf.c"
#include "functions/fills/management/toggleWideFillOf.c"
#include "functions/fills/management/topFill.c"

/* Span Buffer Operations */
#include "functions/spans/clearSpanBuffer.c"
#include "functions/spans/displaySpanBufferAt.c"
#include "functions/spans/loadSpanBufferFrom.c"

/* Bezier Operations */
#include "functions/beziers/adjustWideBezierLeftwidthoffsetendX.c"
#include "functions/beziers/adjustWideBezierRightwidthoffsetendX.c"
#include "functions/beziers/computeBezierSplitAtHalf.c"
#include "functions/beziers/computeBeziersplitAt.c"
#include "functions/beziers/computeFinalWideBezierValueswidth.c"
#include "functions/beziers/loadAndSubdivideBezierFromviatoisWide.c"
#include "functions/beziers/loadBeziersegmentleftFillrightFilloffset.c"
#include "functions/beziers/loadWideBezierlineFillleftFillrightFilln.c"
#include "functions/beziers/stepToFirstBezierInat.c"
#include "functions/beziers/stepToFirstWideBezierInat.c"
#include "functions/beziers/stepToNextWideBezierInat.c"
#include "functions/beziers/subdivideBezier.c"
#include "functions/beziers/subdivideBezierFrom.c"
#include "functions/beziers/subdivideToBeMonotonInX.c"
#include "functions/beziers/subdivideToBeMonotonInY.c"
#include "functions/beziers/subdivideToBeMonotoninX_1.c"

/* Line Operations */
#include "functions/lines/adjustWideLineafterSteppingFromto.c"
#include "functions/lines/loadWideLinefromtolineFillleftFillrightFill.c"
#include "functions/lines/stepToFirstLineInat.c"
#include "functions/lines/stepToFirstWideLineInat.c"

/* Primitives - Shapes */
#include "functions/primitives/shapes/primitiveAddBezier.c"
#include "functions/primitives/shapes/primitiveAddBezierShape.c"
#include "functions/primitives/shapes/primitiveAddCompressedShape.c"
#include "functions/primitives/shapes/primitiveAddLine.c"
#include "functions/primitives/shapes/primitiveAddOval.c"
#include "functions/primitives/shapes/primitiveAddPolygon.c"
#include "functions/primitives/shapes/primitiveAddRect.c"

/* Primitives - Fills */
#include "functions/primitives/fills/primitiveAddBitmapFill.c"
#include "functions/primitives/fills/primitiveAddGradientFill.c"
#include "functions/primitives/fills/primitiveMergeFillFrom.c"
#include "functions/primitives/fills/primitiveNextFillEntry.c"
#include "functions/primitives/fills/primitiveRegisterExternalFill.c"

/* Primitives - Edges */
#include "functions/primitives/edges/primitiveAddActiveEdgeEntry.c"
#include "functions/primitives/edges/primitiveChangedActiveEdgeEntry.c"
#include "functions/primitives/edges/primitiveNextActiveEdgeEntry.c"
#include "functions/primitives/edges/primitiveNextGlobalEdgeEntry.c"
#include "functions/primitives/edges/primitiveRegisterExternalEdge.c"

/* Primitives - Rendering */
#include "functions/primitives/rendering/primitiveAbortProcessing.c"
#include "functions/primitives/rendering/primitiveDisplaySpanBuffer.c"
#include "functions/primitives/rendering/primitiveFinishedProcessing.c"
#include "functions/primitives/rendering/primitiveInitializeProcessing.c"
#include "functions/primitives/rendering/primitiveRenderAllScanlines.c"
#include "functions/primitives/rendering/primitiveRenderImage.c"
#include "functions/primitives/rendering/primitiveRenderScanline.c"

/* Primitives - Configuration */
#include "functions/primitives/config/primitiveGetAALevel.c"
#include "functions/primitives/config/primitiveGetClipRect.c"
#include "functions/primitives/config/primitiveGetDepth.c"
#include "functions/primitives/config/primitiveGetOffset.c"
#include "functions/primitives/config/primitiveSetAALevel.c"
#include "functions/primitives/config/primitiveSetBitBltPlugin.c"
#include "functions/primitives/config/primitiveSetClipRect.c"
#include "functions/primitives/config/primitiveSetColorTransform.c"
#include "functions/primitives/config/primitiveSetDepth.c"
#include "functions/primitives/config/primitiveSetEdgeTransform.c"
#include "functions/primitives/config/primitiveSetOffset.c"

/* Primitives - Buffers */
#include "functions/primitives/buffers/primitiveCopyBuffer.c"
#include "functions/primitives/buffers/primitiveInitializeBuffer.c"
#include "functions/primitives/buffers/primitiveNeedsFlush.c"
#include "functions/primitives/buffers/primitiveNeedsFlushPut.c"

/* Primitives - Statistics */
#include "functions/primitives/stats/primitiveDoProfileStats.c"
#include "functions/primitives/stats/primitiveGetAllStats.c"
#include "functions/primitives/stats/primitiveGetBezierStats.c"
#include "functions/primitives/stats/primitiveGetCounts.c"
#include "functions/primitives/stats/primitiveGetFailureReason.c"
#include "functions/primitives/stats/primitiveGetTimes.c"


/*** Exports ***/

#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "B2DPlugin";
void *B2DPlugin_exports[][3] = {
    {(void *)_m, "getModuleName", (void *)getModuleName},
    {(void *)_m, "initialiseModule", (void *)initialiseModule},
    {(void *)_m, "moduleUnloaded", (void *)moduleUnloaded},
    {(void *)_m, "primitiveAbortProcessing\000\002\003",
     (void *)primitiveAbortProcessing},
    {(void *)_m, "primitiveAddActiveEdgeEntry\000\002\003",
     (void *)primitiveAddActiveEdgeEntry},
    {(void *)_m, "primitiveAddBezier\000\002\003", (void *)primitiveAddBezier},
    {(void *)_m, "primitiveAddBezierShape\000\002\003",
     (void *)primitiveAddBezierShape},
    {(void *)_m, "primitiveAddBitmapFill\000\002\003",
     (void *)primitiveAddBitmapFill},
    {(void *)_m, "primitiveAddCompressedShape\000\002\003",
     (void *)primitiveAddCompressedShape},
    {(void *)_m, "primitiveAddGradientFill\000\002\003",
     (void *)primitiveAddGradientFill},
    {(void *)_m, "primitiveAddLine\000\002\003", (void *)primitiveAddLine},
    {(void *)_m, "primitiveAddOval\000\002\003", (void *)primitiveAddOval},
    {(void *)_m, "primitiveAddPolygon\000\002\003",
     (void *)primitiveAddPolygon},
    {(void *)_m, "primitiveAddRect\000\002\003", (void *)primitiveAddRect},
    {(void *)_m, "primitiveChangedActiveEdgeEntry\000\002\003",
     (void *)primitiveChangedActiveEdgeEntry},
    {(void *)_m, "primitiveCopyBuffer\000\001\003",
     (void *)primitiveCopyBuffer},
    {(void *)_m, "primitiveDisplaySpanBuffer\000\002\000",
     (void *)primitiveDisplaySpanBuffer},
    {(void *)_m, "primitiveDoProfileStats\000\000\003",
     (void *)primitiveDoProfileStats},
    {(void *)_m, "primitiveFinishedProcessing\000\002\003",
     (void *)primitiveFinishedProcessing},
    {(void *)_m, "primitiveGetAALevel\000\002\003",
     (void *)primitiveGetAALevel},
    {(void *)_m, "primitiveGetAllStats\000\002\003",
     (void *)primitiveGetAllStats},
    {(void *)_m, "primitiveGetBezierStats\000\002\003",
     (void *)primitiveGetBezierStats},
    {(void *)_m, "primitiveGetClipRect\000\002\003",
     (void *)primitiveGetClipRect},
    {(void *)_m, "primitiveGetCounts\000\002\003", (void *)primitiveGetCounts},
    {(void *)_m, "primitiveGetDepth\000\002\003", (void *)primitiveGetDepth},
    {(void *)_m, "primitiveGetFailureReason\000\002\003",
     (void *)primitiveGetFailureReason},
    {(void *)_m, "primitiveGetOffset\000\002\003", (void *)primitiveGetOffset},
    {(void *)_m, "primitiveGetTimes\000\002\003", (void *)primitiveGetTimes},
    {(void *)_m, "primitiveInitializeBuffer\000\001\003",
     (void *)primitiveInitializeBuffer},
    {(void *)_m, "primitiveInitializeProcessing\000\002\003",
     (void *)primitiveInitializeProcessing},
    {(void *)_m, "primitiveMergeFillFrom\000\002\003",
     (void *)primitiveMergeFillFrom},
    {(void *)_m, "primitiveNeedsFlush\000\002\003",
     (void *)primitiveNeedsFlush},
    {(void *)_m, "primitiveNeedsFlushPut\000\002\003",
     (void *)primitiveNeedsFlushPut},
    {(void *)_m, "primitiveNextActiveEdgeEntry\000\002\003",
     (void *)primitiveNextActiveEdgeEntry},
    {(void *)_m, "primitiveNextFillEntry\000\004\003",
     (void *)primitiveNextFillEntry},
    {(void *)_m, "primitiveNextGlobalEdgeEntry\000\002\003",
     (void *)primitiveNextGlobalEdgeEntry},
    {(void *)_m, "primitiveRegisterExternalEdge\000\002\003",
     (void *)primitiveRegisterExternalEdge},
    {(void *)_m, "primitiveRegisterExternalFill\000\002\003",
     (void *)primitiveRegisterExternalFill},
    {(void *)_m, "primitiveRenderAllScanlines\000\377\000",
     (void *)primitiveRenderAllScanlines},
    {(void *)_m, "primitiveRenderImage\000\377\000",
     (void *)primitiveRenderImage},
    {(void *)_m, "primitiveRenderScanline\000\377\000",
     (void *)primitiveRenderScanline},
    {(void *)_m, "primitiveSetAALevel\000\002\003",
     (void *)primitiveSetAALevel},
    {(void *)_m, "primitiveSetBitBltPlugin\000\001\003",
     (void *)primitiveSetBitBltPlugin},
    {(void *)_m, "primitiveSetClipRect\000\002\003",
     (void *)primitiveSetClipRect},
    {(void *)_m, "primitiveSetColorTransform\000\002\003",
     (void *)primitiveSetColorTransform},
    {(void *)_m, "primitiveSetDepth\000\002\003", (void *)primitiveSetDepth},
    {(void *)_m, "primitiveSetEdgeTransform\000\002\003",
     (void *)primitiveSetEdgeTransform},
    {(void *)_m, "primitiveSetOffset\000\002\003", (void *)primitiveSetOffset},
    {(void *)_m, "setInterpreter", (void *)setInterpreter},
    {NULL, NULL, NULL}};

#else // ifdef SQ_BUILTIN_PLUGIN

#if SPURVM
EXPORT(signed short) primitiveAbortProcessingMetadata = 515;
EXPORT(signed short) primitiveAddActiveEdgeEntryMetadata = 515;
EXPORT(signed short) primitiveAddBezierMetadata = 515;
EXPORT(signed short) primitiveAddBezierShapeMetadata = 515;
EXPORT(signed short) primitiveAddBitmapFillMetadata = 515;
EXPORT(signed short) primitiveAddCompressedShapeMetadata = 515;
EXPORT(signed short) primitiveAddGradientFillMetadata = 515;
EXPORT(signed short) primitiveAddLineMetadata = 515;
EXPORT(signed short) primitiveAddOvalMetadata = 515;
EXPORT(signed short) primitiveAddPolygonMetadata = 515;
EXPORT(signed short) primitiveAddRectMetadata = 515;
EXPORT(signed short) primitiveChangedActiveEdgeEntryMetadata = 515;
EXPORT(signed short) primitiveCopyBufferMetadata = 259;
EXPORT(signed short) primitiveDisplaySpanBufferMetadata = 0x200;
EXPORT(signed short) primitiveDoProfileStatsMetadata = 3;
EXPORT(signed short) primitiveFinishedProcessingMetadata = 515;
EXPORT(signed short) primitiveGetAALevelMetadata = 515;
EXPORT(signed short) primitiveGetAllStatsMetadata = 515;
EXPORT(signed short) primitiveGetBezierStatsMetadata = 515;
EXPORT(signed short) primitiveGetClipRectMetadata = 515;
EXPORT(signed short) primitiveGetCountsMetadata = 515;
EXPORT(signed short) primitiveGetDepthMetadata = 515;
EXPORT(signed short) primitiveGetFailureReasonMetadata = 515;
EXPORT(signed short) primitiveGetOffsetMetadata = 515;
EXPORT(signed short) primitiveGetTimesMetadata = 515;
EXPORT(signed short) primitiveInitializeBufferMetadata = 259;
EXPORT(signed short) primitiveInitializeProcessingMetadata = 515;
EXPORT(signed short) primitiveMergeFillFromMetadata = 515;
EXPORT(signed short) primitiveNeedsFlushMetadata = 515;
EXPORT(signed short) primitiveNeedsFlushPutMetadata = 515;
EXPORT(signed short) primitiveNextActiveEdgeEntryMetadata = 515;
EXPORT(signed short) primitiveNextFillEntryMetadata = 1027;
EXPORT(signed short) primitiveNextGlobalEdgeEntryMetadata = 515;
EXPORT(signed short) primitiveRegisterExternalEdgeMetadata = 515;
EXPORT(signed short) primitiveRegisterExternalFillMetadata = 515;
EXPORT(signed short) primitiveSetAALevelMetadata = 515;
EXPORT(signed short) primitiveSetBitBltPluginMetadata = 259;
EXPORT(signed short) primitiveSetClipRectMetadata = 515;
EXPORT(signed short) primitiveSetColorTransformMetadata = 515;
EXPORT(signed short) primitiveSetDepthMetadata = 515;
EXPORT(signed short) primitiveSetEdgeTransformMetadata = 515;
EXPORT(signed short) primitiveSetOffsetMetadata = 515;
#endif // SPURVM

#endif // ifdef SQ_BUILTIN_PLUGIN
