#EXTRALIBS:=-undefined dynamic_lookup
SRCDIRS:=$(PLATDIR)/unix/plugins/SerialPlugin
INCDIRS:=$(PLUGINSRCDIR)/SerialPlugin/cross
LIBSRC:=SerialPlugin.c sqUnixSerial.c

include ../common/Makefile.plugin
