#
# FileAttributesPlugin uses sq2uxPath() and ux2sqPath(), provided by sqUnixCharConv.h
#
#
SRCDIRS:=$(PLATDIR)/unix/vm $(PLUGINSRCDIR)/FileAttributesPlugin/unix
INCDIRS:=$(PLATDIR)/unix/vm $(PLUGINSRCDIR)/FileAttributesPlugin/unix
LIBSRC:=FileAttributesPlugin.c sqUnixCharConv.c faSupport.c faCommon.c

include ../common/Makefile.plugin

