EXTRALIBS:=-undefined dynamic_lookup -framework Foundation
CFLAGS:=-x objective-c
INCDIRS:=$(PLUGINSRCDIR)/SqueakObjectiveC/macos
SRCDIRS:=$(PLUGINSRCDIR)/SqueakObjectiveC/macos
LIBSRC:=squeakProxy.m squeakSUnitTester.m

include ../common/Makefile.plugin
