/* Automatically generated by
        VMPluginCodeGenerator VMMaker.oscog-eem.3599 uuid:
   1a32964f-d425-4ed5-b830-6e8ce3d98688
        (* Compiler-eem.518)
   from
        VMProfileMacSupportPlugin VMMaker.oscog-eem.3599 uuid:
   1a32964f-d425-4ed5-b830-6e8ce3d98688
 */
#if defined(__clang__) || defined(__GNUC__)
static const char __buildInfo[] __attribute__((unused)) =
    "VMProfileMacSupportPlugin VMMaker.oscog-eem.3599 uuid: "
    "1a32964f-d425-4ed5-b830-6e8ce3d98688 " __DATE__;
#else
static const char __buildInfo[] =
    "VMProfileMacSupportPlugin VMMaker.oscog-eem.3599 uuid: "
    "1a32964f-d425-4ed5-b830-6e8ce3d98688 " __DATE__;
#endif

#include "config.h"
#include "sqMathShim.h"
#include <dlfcn.h>
#include <mach-o/dyld.h>
#include <mach-o/getsect.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"           /* Configuration options */
#include "sqPlatformSpecific.h" /* Platform specific definitions */
#include "sqVirtualMachine.h"   /*  The virtual machine proxy definition */

#include "sqMemoryAccess.h"

#define true 1
#define false 0
#define null 0 /* using 'null' because nil is predefined in Think C */
#undef EXPORT
#define EXPORT(returnType) static returnType
#define INT_EXT "(i)"

/*** Function Prototypes ***/
EXPORT(const char *) getModuleName(void);
EXPORT(sqInt) primitiveDLSym(void);
EXPORT(sqInt) primitiveExecutableModulesAndOffsets(void);
EXPORT(sqInt) primitiveTextSymbols(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);

/*** Variables ***/

extern void *arrayValueOf(sqInt oop);
extern sqInt byteSizeOf(sqInt oop);
extern sqInt classArray(void);
extern sqInt classString(void);
extern sqInt failed(void);
extern void *firstIndexableField(sqInt oop);
extern sqInt instantiateClassindexableSize(sqInt classPointer, sqInt size);
#if !defined(integerValueOf)
extern sqInt integerValueOf(sqInt oop);
#endif
extern sqInt isBytes(sqInt oop);
#if !defined(isIntegerObject)
extern sqInt isIntegerObject(sqInt objectPointer);
#endif
extern sqInt methodReturnValue(sqInt oop);
extern sqInt nilObject(void);
extern sqInt popRemappableOop(void);
extern sqInt positive32BitIntegerFor(unsigned int integerValue);
extern sqInt positive64BitIntegerFor(usqLong integerValue);
extern sqInt primitiveFailFor(sqInt reasonCode);
extern sqInt pushRemappableOop(sqInt oop);
extern sqInt signed32BitIntegerFor(sqInt integerValue);
extern sqInt signed64BitIntegerFor(sqLong integerValue);
extern sqInt stackValue(sqInt offset);
extern sqInt storePointerofObjectwithValue(sqInt index, sqInt oop,
                                           sqInt valuePointer);
extern sqInt topRemappableOop(void);
extern
struct VirtualMachine *interpreterProxy;
static const char *moduleName =
    "VMProfileMacSupportPlugin VMMaker.oscog-eem.3599 " INT_EXT;

/*** Methods ***/

/*	Note: This is hardcoded so it can be run from Squeak.
        The module name is used for validating a module *after*
        it is loaded to check if it does really contain the module
        we're thinking it contains. This is important! */

/* InterpreterPlugin>>#getModuleName */
EXPORT(const char *)
getModuleName(void) { return moduleName; }

/*	Answer the address of the argument in the current process or nil if
 * none. */

/* VMProfileMacSupportPlugin>>#primitiveDLSym */
EXPORT(sqInt)
primitiveDLSym(void) {
  void *addr;
  char *dstPtr;
  sqInt obj;
  char *symbolName;
  sqInt sz;

  /* begin stackEphemeralStringValue: */
  obj = stackValue(0);
  if (!(isBytes(obj))) {
    primitiveFailFor(PrimErrBadArgument);
    symbolName = null;
    goto l1;
  }
  sz = byteSizeOf(obj);
  dstPtr = alloca(sz + 1);
  if (!dstPtr) {
    primitiveFailFor(PrimErrNoCMemory);
    symbolName = null;
    goto l1;
  }
  memcpy(dstPtr, firstIndexableField(obj), sz);
  dstPtr[sz] = 0;
  symbolName = dstPtr;
  /* end stackEphemeralStringValue: */
l1:
  if (symbolName) {
    addr = dlsym(RTLD_SELF, symbolName);
    methodReturnValue(
        (addr ? /* positiveMachineIntegerFor: */
             (BytesPerWord == 8 ? positive64BitIntegerFor(((usqIntptr_t)addr))
                                : positive32BitIntegerFor(((usqIntptr_t)addr)))
              : nilObject()));
  }
  return 0;
}

/*	Answer an Array of quads for executable modules (the VM executable
        and loaded libraries). Each quad is the module's name, its vm address
        relocation in memory, the (unrelocated) start address, and the size. */

/* VMProfileMacSupportPlugin>>#primitiveExecutableModulesAndOffsets */
EXPORT(sqInt)
primitiveExecutableModulesAndOffsets(void) {
  const struct mach_header *h;
  const struct mach_header_64 *h64;
  sqInt i;
  const char *name;
  char *nameObjData;
  sqInt nimages;
  sqInt resultObj;
  const struct section *s;
  const struct section_64 *s64;
  usqIntptr_t size;
  usqIntptr_t slide;
  usqIntptr_t start;
  sqInt valueObj;

  nimages = _dyld_image_count();
  resultObj = instantiateClassindexableSize(classArray(), nimages * 4);
  if (!resultObj) {
    return primitiveFailFor(PrimErrNoMemory);
  }
  pushRemappableOop(resultObj);
  for (i = 0; i < nimages; i += 1) {
    /* impossible start & size */
    start = (size = -1);
    name = _dyld_get_image_name(i);
    slide = _dyld_get_image_vmaddr_slide(i);
#if __x86_64__ || __arm64__
    if ((h64 = ((const struct mach_header_64 *)(_dyld_get_image_header(i))))) {
      if ((s64 = getsectbynamefromheader_64(h64, SEG_TEXT, SECT_TEXT))) {
        start = (s64->addr);
        size = (s64->size);
      }
    }
#else  // __x86_64__ || __arm64__
    if ((h = _dyld_get_image_header(i))) {
      if ((s = getsectbynamefromheader(h, SEG_TEXT, SECT_TEXT))) {
        start = (s->addr);
        size = (s->size);
      }
    }
#endif // __x86_64__ || __arm64__

    valueObj = instantiateClassindexableSize(classString(), strlen(name));
    if (failed()) {
      popRemappableOop();
      return primitiveFailFor(PrimErrNoMemory);
    }
    storePointerofObjectwithValue(i * 4, topRemappableOop(), valueObj);
    nameObjData = arrayValueOf(valueObj);
    memcpy(nameObjData, name, strlen(name));
    valueObj = /* signedMachineIntegerFor: */
        (BytesPerWord == 8 ? signed64BitIntegerFor(slide)
                           : signed32BitIntegerFor(slide));
    if (failed()) {
      popRemappableOop();
      return primitiveFailFor(PrimErrNoMemory);
    }
    storePointerofObjectwithValue((i * 4) + 1, topRemappableOop(), valueObj);
    valueObj = /* positiveMachineIntegerFor: */
        (BytesPerWord == 8 ? positive64BitIntegerFor(start)
                           : positive32BitIntegerFor(start));
    if (failed()) {
      popRemappableOop();
      return primitiveFailFor(PrimErrNoMemory);
    }
    storePointerofObjectwithValue((i * 4) + 2, topRemappableOop(), valueObj);
    valueObj = /* positiveMachineIntegerFor: */
        (BytesPerWord == 8 ? positive64BitIntegerFor(size)
                           : positive32BitIntegerFor(size));
    if (failed()) {
      popRemappableOop();
      return primitiveFailFor(PrimErrNoMemory);
    }
    storePointerofObjectwithValue((i * 4) + 3, topRemappableOop(), valueObj);
  }
  return methodReturnValue(popRemappableOop());
}

/*	Answer an Array of pairs of address, name, for text symbols in the n'th
        loaded module,
        as defined by the _dyld_image_count enumeration. */

/* VMProfileMacSupportPlugin>>#primitiveTextSymbols */
EXPORT(sqInt)
primitiveTextSymbols(void) {
  Dl_info dlInfo;
  Dl_info *dlInfos;
  usqIntptr_t end;
  const struct mach_header *h;
  const struct mach_header_64 *h64;
  sqInt increment;
  sqInt index;
  void *last_saddr;
  sqInt moduleIndex;
  char *nameObjData;
  sqInt ndlInfos;
  sqInt resultObj;
  const struct section *s;
  const struct section_64 *s64;
  usqIntptr_t slide;
  usqIntptr_t start;
  sqInt valueObj;

  end = 0;
  moduleIndex = stackValue(0);
  if (!((isIntegerObject(moduleIndex)) &&
        ((((moduleIndex = integerValueOf(moduleIndex))) >= 0) &&
         ((_dyld_get_image_name(moduleIndex)))))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  start = 0;
  slide = _dyld_get_image_vmaddr_slide(moduleIndex);
#if __x86_64__ || __arm64__
  if ((h64 = ((const struct mach_header_64 *)(_dyld_get_image_header(
           moduleIndex))))) {
    if ((s64 = getsectbynamefromheader_64(h64, SEG_TEXT, SECT_TEXT))) {
      start = ((s64->addr)) + slide;
      end = start + ((s64->size));
    }
  }
#else  // __x86_64__ || __arm64__
  if ((h = _dyld_get_image_header(moduleIndex))) {
    if ((s = getsectbynamefromheader(h, SEG_TEXT, SECT_TEXT))) {
      start = (s->addr);
      end = start + ((s->size));
    }
  }
#endif // __x86_64__ || __arm64__

  if (!start) {
    return primitiveFailFor(PrimErrOperationFailed);
  }
  if (!((dlInfos =
             malloc((sizeof(Dl_info)) * ((ndlInfos = (increment = 0x400))))))) {
    return primitiveFailFor(PrimErrNoCMemory);
  }
  index = 0;
  last_saddr = null;

  /* Yes, dear reader, one could use binary search to reduce the amount of
     effort.  But when this author attempted to do so, he achieved only a
     marginal improvement for a substantial increase in complexity. So KISS and
     do a linear scan, looking ahead 64 bytes to reduce overhead as simply as
     possible. 64 gave best results when tried on the VM module of an
     ARMv8/aarch64 VM; about 2.5x a naive step by sizeof(void *). */
  while ((start < end) && ((dladdr(((void *)start), dlInfos + index)) != 0)) {
    if (((start + 64) < end) &&
        (((dladdr(((void *)(start + 64)), (&dlInfo))) != 0) &&
         (((dlInfo.dli_saddr)) == (((dlInfos[index]).dli_saddr))))) {
      start = (start + 64) + (sizeof(void *));
    } else {
      start += sizeof(void *);
    }
    if (last_saddr != (((dlInfos[index]).dli_saddr))) {
      last_saddr = ((dlInfos[index]).dli_saddr);
      if (((index += 1)) == ndlInfos) {
        dlInfos = reallocf(dlInfos, (sizeof(Dl_info)) * (ndlInfos + increment));
        if (!dlInfos) {
          return primitiveFailFor(PrimErrNoCMemory);
        }
        ndlInfos += increment;
        increment = increment * 2;
      }
    }
  }
  resultObj = instantiateClassindexableSize(classArray(), index * 2);
  if (!resultObj) {
    free(dlInfos);
    return primitiveFailFor(PrimErrNoMemory);
  }
  pushRemappableOop(resultObj);
  ndlInfos = index;
  index = 0;
  while (index < ndlInfos) {
    valueObj = /* positiveMachineIntegerFor: */
        (BytesPerWord == 8
             ? positive64BitIntegerFor(((dlInfos[index]).dli_saddr))
             : positive32BitIntegerFor(((dlInfos[index]).dli_saddr)));
    if (failed()) {
      free(dlInfos);
      popRemappableOop();
      return primitiveFailFor(PrimErrNoMemory);
    }
    storePointerofObjectwithValue(index * 2, topRemappableOop(), valueObj);
    valueObj = instantiateClassindexableSize(
        classString(), strlen(((dlInfos[index]).dli_sname)));
    if (failed()) {
      free(dlInfos);
      popRemappableOop();
      return primitiveFailFor(PrimErrNoMemory);
    }
    storePointerofObjectwithValue((index * 2) + 1, topRemappableOop(),
                                  valueObj);
    nameObjData = arrayValueOf(valueObj);
    memcpy(nameObjData, ((dlInfos[index]).dli_sname),
           strlen(((dlInfos[index]).dli_sname)));
    index += 1;
  }
  free(dlInfos);
  return methodReturnValue(popRemappableOop());
}

/*	Note: This is coded so that it can be run in Squeak. */

/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine *anInterpreter) {
  sqInt ok;

  interpreterProxy = anInterpreter;

  /* This may seem tautological, but in a real plugin it checks that the VM
     provides the version the plugin was compiled against which is the version
     the plugin expects. */
  ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR)) &&
       ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
  if (ok) {

  }
  return ok;
}

/*** Exports ***/


static char _m[] = "VMProfileMacSupportPlugin";
void *VMProfileMacSupportPlugin_exports[][3] = {
    {(void *)_m, "getModuleName", (void *)getModuleName},
    {(void *)_m, "primitiveDLSym\000\000\000", (void *)primitiveDLSym},
    {(void *)_m, "primitiveExecutableModulesAndOffsets\000\377\000",
     (void *)primitiveExecutableModulesAndOffsets},
    {(void *)_m, "primitiveTextSymbols\000\000\000",
     (void *)primitiveTextSymbols},
    {(void *)_m, "setInterpreter", (void *)setInterpreter},
    {NULL, NULL, NULL}};

