/* Automatically generated by
        SmartSyntaxPluginCodeGenerator VMMaker.oscog-eem.3477 uuid:
   2de18dc7-c0eb-403e-953d-0fddeb535cfb (Compiler-eem.512) from AsynchFilePlugin
   VMMaker.oscog-eem.3477 uuid: 2de18dc7-c0eb-403e-953d-0fddeb535cfb
 */
#if defined(__clang__) || defined(__GNUC__)
static const char __buildInfo[] __attribute__((unused)) =
    "AsynchFilePlugin VMMaker.oscog-eem.3477 uuid: "
    "2de18dc7-c0eb-403e-953d-0fddeb535cfb " __DATE__;
#else
static const char __buildInfo[] =
    "AsynchFilePlugin VMMaker.oscog-eem.3477 uuid: "
    "2de18dc7-c0eb-403e-953d-0fddeb535cfb " __DATE__;
#endif

#include "config.h"
#include "sqMathShim.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"           /* Configuration options */
#include "sqPlatformSpecific.h" /* Platform specific definitions */
#include "sqVirtualMachine.h"   /*  The virtual machine proxy definition */

#include "AsynchFilePlugin.h"
#include "sqMemoryAccess.h"

#define true 1
#define false 0
#define null 0 /* using 'null' because nil is predefined in Think C */
#undef EXPORT
#define EXPORT(returnType) static returnType
#define INT_EXT "(i)"

/*** Function Prototypes ***/
EXPORT(const char *) getModuleName(void);
EXPORT(sqInt) initialiseModule(void);
EXPORT(sqInt) moduleUnloaded(char *aModuleName);
EXPORT(sqInt) primitiveAsyncFileClose(void);
EXPORT(sqInt) primitiveAsyncFileOpen(void);
EXPORT(sqInt) primitiveAsyncFileReadResult(void);
EXPORT(sqInt) primitiveAsyncFileReadStart(void);
EXPORT(sqInt) primitiveAsyncFileWriteResult(void);
EXPORT(sqInt) primitiveAsyncFileWriteStart(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);
EXPORT(sqInt) shutdownModule(void);

/*** Variables ***/

extern sqInt booleanValueOf(sqInt obj);
extern sqInt byteSizeOf(sqInt oop);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 17)
extern sqInt bytesPerElement(sqInt oop);
#else
#define bytesPerElement(oop) 0
#endif
extern sqInt classByteArray(void);
extern sqInt failed(void);
extern void *firstIndexableField(sqInt oop);
extern sqInt instantiateClassindexableSize(sqInt classPointer, sqInt size);
#if !defined(integerObjectOf)
extern sqInt integerObjectOf(sqInt value);
#endif
#if !defined(integerValueOf)
extern sqInt integerValueOf(sqInt oop);
#endif
extern void *ioLoadFunctionFrom(char *functionName, char *moduleName);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 15)
extern sqInt isBooleanObject(sqInt oop);
#else
#define isBooleanObject(oop) 0
#endif
extern sqInt isBytes(sqInt oop);
#if !defined(isIntegerObject)
extern sqInt isIntegerObject(sqInt objectPointer);
#endif
extern sqInt methodReturnValue(sqInt oop);
extern sqInt pop(sqInt nItems);
extern sqInt primitiveFail(void);
extern sqInt primitiveFailFor(sqInt reasonCode);
extern sqInt stackValue(sqInt offset);
extern
struct VirtualMachine *interpreterProxy;
static const char *moduleName =
    "AsynchFilePlugin VMMaker.oscog-eem.3477 " INT_EXT;
static void *sCOAFfn;

/*** Methods ***/

/*	Note: This is hardcoded so it can be run from Squeak.
        The module name is used for validating a module *after*
        it is loaded to check if it does really contain the module
        we're thinking it contains. This is important! */

/* InterpreterPlugin>>#getModuleName */
EXPORT(const char *)
getModuleName(void) { return moduleName; }

/*	Initialise the module */

/* AsynchFilePlugin>>#initialiseModule */
EXPORT(sqInt)
initialiseModule(void) {
  sCOAFfn =
      ioLoadFunctionFrom("secCanOpenAsyncFileOfSizeWritable", "SecurityPlugin");
  return asyncFileInit();
}

/*	The module with the given name was just unloaded.
        Make sure we have no dangling references. */

/* AsynchFilePlugin>>#moduleUnloaded: */
EXPORT(sqInt)
moduleUnloaded(char *aModuleName) {
  if (!(strcmp(aModuleName, "SecurityPlugin"))) {
    sCOAFfn = 0;
  }
  return 0;
}

/* AsynchFilePlugin>>#primitiveAsyncFileClose: */
EXPORT(sqInt)
primitiveAsyncFileClose(void) {
  AsyncFile *f;
  sqInt fh;

  fh = stackValue(0);

  /* begin asyncFileValueOf: */
  if ((isBytes(fh)) && ((byteSizeOf(fh)) == (sizeof(AsyncFile)))) {
    f = ((AsyncFile *)(firstIndexableField(fh)));
    goto l1;
  }
  primitiveFailFor(PrimErrBadArgument);
  f = null;
  /* end asyncFileValueOf: */
l1:
  if (failed()) {
    return null;
  }
  asyncFileClose(f);
  if (!(failed())) {
    pop(1);
  }
  return null;
}

/* AsynchFilePlugin>>#primitiveAsyncFileOpen:forWrite:semaIndex: */
EXPORT(sqInt)
primitiveAsyncFileOpen(void) {
  AsyncFile *f;
  char *fileName;
  sqInt fileNameSize;
  sqInt fOop;
  sqInt okToOpen;
  sqInt semaIndex;
  sqInt writeFlag;

  if (!((isBytes(stackValue(2))) &&
        ((isBooleanObject(stackValue(1))) &&
         (isIntegerObject((semaIndex = stackValue(0))))))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  fileName = firstIndexableField(stackValue(2));
  writeFlag = booleanValueOf(stackValue(1));
  semaIndex = integerValueOf(semaIndex);
  fileNameSize = byteSizeOf(((sqInt)((fileName)-BaseHeaderSize)));

  /* If the security plugin can be loaded, use it to check for permission.
     If not, assume it's ok */
  if (sCOAFfn) {
    okToOpen = ((sqInt (*)(char *, sqInt, sqInt))sCOAFfn)(
        fileName, fileNameSize, writeFlag);
    if (!okToOpen) {
      return primitiveFail();
    }
  }
  fOop = instantiateClassindexableSize(classByteArray(), sizeof(AsyncFile));

  /* begin asyncFileValueOf: */
  if ((isBytes(fOop)) && ((byteSizeOf(fOop)) == (sizeof(AsyncFile)))) {
    f = ((AsyncFile *)(firstIndexableField(fOop)));
    goto l1;
  }
  primitiveFailFor(PrimErrBadArgument);
  f = null;
  /* end asyncFileValueOf: */
l1:
  if (!(failed())) {
    asyncFileOpen(f, fileName, fileNameSize, writeFlag, semaIndex);
  }
  if (!(failed())) {
    methodReturnValue(fOop);
  }
  return null;
}

/* AsynchFilePlugin>>#primitiveAsyncFileReadResult:intoBuffer:at:count: */
EXPORT(sqInt)
primitiveAsyncFileReadResult(void) {
  sqInt buffer;
  char *bufferPtr;
  sqInt bufferSize;
  sqInt count;
  AsyncFile *f;
  sqInt fhandle;
  sqInt num;
  sqInt r;
  sqInt scaleFactor;
  sqInt start;
  sqInt startIndex;

  if (!((isIntegerObject((start = stackValue(1)))) &&
        (isIntegerObject((num = stackValue(0)))))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  fhandle = stackValue(3);
  buffer = stackValue(2);
  start = integerValueOf(start);
  num = integerValueOf(num);

  /* begin asyncFileValueOf: */
  if ((isBytes(fhandle)) && ((byteSizeOf(fhandle)) == (sizeof(AsyncFile)))) {
    f = ((AsyncFile *)(firstIndexableField(fhandle)));
    goto l1;
  }
  primitiveFailFor(PrimErrBadArgument);
  f = null;
  /* end asyncFileValueOf: */
l1:
  count = num;
  startIndex = start;
  bufferSize = byteSizeOf(buffer);
  if (!(isBytes(buffer))) {
    scaleFactor = bytesPerElement(buffer);
    count = count * scaleFactor;
    startIndex = ((startIndex - 1) * scaleFactor) + 1;
  }

  /* convert word counts to byte counts */
  if (!((startIndex >= 1) && (((startIndex + count) - 1) <= bufferSize))) {
    return primitiveFailFor(PrimErrBadIndex);
  }

  /* adjust for zero-origin indexing */
  bufferPtr = ((((char *)(firstIndexableField(buffer)))) + startIndex) - 1;
  r = asyncFileReadResult(f, bufferPtr, count);
  if (!(failed())) {
    methodReturnValue(integerObjectOf(r));
  }
  return null;
}

/* AsynchFilePlugin>>#primitiveAsyncFileReadStart:fPosition:count: */
EXPORT(sqInt)
primitiveAsyncFileReadStart(void) {
  sqInt count;
  AsyncFile *f;
  sqInt fHandle;
  sqInt fPosition;

  if (!((isIntegerObject((fPosition = stackValue(1)))) &&
        (isIntegerObject((count = stackValue(0)))))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  fHandle = stackValue(2);
  fPosition = integerValueOf(fPosition);
  count = integerValueOf(count);

  /* begin asyncFileValueOf: */
  if ((isBytes(fHandle)) && ((byteSizeOf(fHandle)) == (sizeof(AsyncFile)))) {
    f = ((AsyncFile *)(firstIndexableField(fHandle)));
    goto l1;
  }
  primitiveFailFor(PrimErrBadArgument);
  f = null;
  /* end asyncFileValueOf: */
l1:
  if (failed()) {
    return null;
  }
  asyncFileReadStart(f, fPosition, count);
  if (!(failed())) {
    pop(3);
  }
  return null;
}

/* AsynchFilePlugin>>#primitiveAsyncFileWriteResult: */
EXPORT(sqInt)
primitiveAsyncFileWriteResult(void) {
  AsyncFile *f;
  sqInt fHandle;
  sqInt r;

  fHandle = stackValue(0);

  /* begin asyncFileValueOf: */
  if ((isBytes(fHandle)) && ((byteSizeOf(fHandle)) == (sizeof(AsyncFile)))) {
    f = ((AsyncFile *)(firstIndexableField(fHandle)));
    goto l1;
  }
  primitiveFailFor(PrimErrBadArgument);
  f = null;
  /* end asyncFileValueOf: */
l1:
  if (failed()) {
    return null;
  }
  r = asyncFileWriteResult(f);
  if (!(failed())) {
    methodReturnValue(integerObjectOf(r));
  }
  return null;
}

/* AsynchFilePlugin>>#primitiveAsyncFileWriteStart:fPosition:fromBuffer:at:count:
 */
EXPORT(sqInt)
primitiveAsyncFileWriteStart(void) {
  sqInt buffer;
  char *bufferPtr;
  sqInt bufferSize;
  sqInt count;
  AsyncFile *f;
  sqInt fHandle;
  sqInt fPosition;
  sqInt num;
  sqInt scaleFactor;
  sqInt start;
  sqInt startIndex;

  if (!((isIntegerObject((fPosition = stackValue(3)))) &&
        ((isIntegerObject((start = stackValue(1)))) &&
         (isIntegerObject((num = stackValue(0))))))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  fHandle = stackValue(4);
  fPosition = integerValueOf(fPosition);
  buffer = stackValue(2);
  start = integerValueOf(start);
  num = integerValueOf(num);

  /* begin asyncFileValueOf: */
  if ((isBytes(fHandle)) && ((byteSizeOf(fHandle)) == (sizeof(AsyncFile)))) {
    f = ((AsyncFile *)(firstIndexableField(fHandle)));
    goto l1;
  }
  primitiveFailFor(PrimErrBadArgument);
  f = null;
  /* end asyncFileValueOf: */
l1:
  count = num;
  startIndex = start;
  bufferSize = byteSizeOf(buffer);
  if (!(isBytes(buffer))) {
    scaleFactor = bytesPerElement(buffer);
    count = count * scaleFactor;
    startIndex = ((startIndex - 1) * scaleFactor) + 1;
  }

  /* covert word counts to byte counts */
  if (!((startIndex >= 1) && (((startIndex + count) - 1) <= bufferSize))) {
    return primitiveFailFor(PrimErrBadIndex);
  }

  /* adjust for zero-origin indexing */
  bufferPtr = ((((char *)(firstIndexableField(buffer)))) + startIndex) - 1;
  asyncFileWriteStart(f, fPosition, bufferPtr, count);
  if (!(failed())) {
    pop(5);
  }
  return null;
}

/*	Note: This is coded so that it can be run in Squeak. */

/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine *anInterpreter) {
  sqInt ok;

  interpreterProxy = anInterpreter;

  /* This may seem tautological, but in a real plugin it checks that the VM
     provides the version the plugin was compiled against which is the version
     the plugin expects. */
  ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR)) &&
       ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
  if (ok) {

  }
  return ok;
}

/*	Initialise the module */

/* AsynchFilePlugin>>#shutdownModule */
EXPORT(sqInt)
shutdownModule(void) { return asyncFileShutdown(); }

/*** Exports ***/


static char _m[] = "AsynchFilePlugin";
void *AsynchFilePlugin_exports[][3] = {
    {(void *)_m, "getModuleName", (void *)getModuleName},
    {(void *)_m, "initialiseModule", (void *)initialiseModule},
    {(void *)_m, "moduleUnloaded", (void *)moduleUnloaded},
    {(void *)_m, "primitiveAsyncFileClose\000\001\000",
     (void *)primitiveAsyncFileClose},
    {(void *)_m, "primitiveAsyncFileOpen\000\000\000",
     (void *)primitiveAsyncFileOpen},
    {(void *)_m, "primitiveAsyncFileReadResult\000\001\000",
     (void *)primitiveAsyncFileReadResult},
    {(void *)_m, "primitiveAsyncFileReadStart\000\001\000",
     (void *)primitiveAsyncFileReadStart},
    {(void *)_m, "primitiveAsyncFileWriteResult\000\001\000",
     (void *)primitiveAsyncFileWriteResult},
    {(void *)_m, "primitiveAsyncFileWriteStart\000\001\000",
     (void *)primitiveAsyncFileWriteStart},
    {(void *)_m, "setInterpreter", (void *)setInterpreter},
    {(void *)_m, "shutdownModule", (void *)shutdownModule},
    {NULL, NULL, NULL}};

