EXTRALIBS:=-undefined dynamic_lookup -framework Foundation
CFLAGS:=-x objective-c
INCDIRS:=$(PLUGINSRCDIR)/SqueakObjectiveC/ios
SRCDIRS:=$(PLUGINSRCDIR)/SqueakObjectiveC/ios
LIBSRC:=squeakProxy.m squeakSUnitTester.m

include ../common/Makefile.plugin
