/* Automatically generated by
        SmartSyntaxPluginCodeGenerator VMMaker.oscog-eem.3664 uuid:
   bec3b39b-863c-43da-aa70-36c06b3b38bf (Compiler-eem.520) from BitBltSimulation
   VMMaker.oscog-eem.3664 uuid: bec3b39b-863c-43da-aa70-36c06b3b38bf
 */
#if defined(__clang__) || defined(__GNUC__)
static const char __buildInfo[] __attribute__((unused)) =
    "BitBltSimulation VMMaker.oscog-eem.3664 uuid: "
    "bec3b39b-863c-43da-aa70-36c06b3b38bf " __DATE__;
#else
static const char __buildInfo[] =
    "BitBltSimulation VMMaker.oscog-eem.3664 uuid: "
    "bec3b39b-863c-43da-aa70-36c06b3b38bf " __DATE__;
#endif

#include "config.h"
#include "sqMathShim.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"           /* Configuration options */
#include "sqPlatformSpecific.h" /* Platform specific definitions */
#include "sqVirtualMachine.h"   /*  The virtual machine proxy definition */

#include "sqAssert.h"
#ifdef ENABLE_FAST_BLT
#include "BitBltDispatch.h"
#else
// to handle the unavoidable decl in the spec of copyBitsFallback();
#define operation_t void
#endif
#include "sqMemoryAccess.h"

#define true 1
#define false 0
#define null 0 /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
#define EXPORT(returnType) static returnType
#define INT_EXT "(i)"
#else
#define INT_EXT "(e)"
#endif

/*** Constants ***/
#define AllOnes 0xFFFFFFFFU
#define AlphaIndex 3
#define BBClipHeightIndex 13
#define BBClipWidthIndex 12
#define BBClipXIndex 10
#define BBClipYIndex 11
#define BBColorMapIndex 14
#define BBDestFormIndex 0
#define BBDestXIndex 4
#define BBDestYIndex 5
#define BBHalftoneFormIndex 2
#define BBHeightIndex 7
#define BBRuleIndex 3
#define BBSourceFormIndex 1
#define BBSourceXIndex 8
#define BBSourceYIndex 9
#define BBWarpBase 15
#define BBWidthIndex 6
#define BEBitBltIndex 2
#define BinaryPoint 14
#define BlueIndex 2
#define ColorMapFixedPart 2
#define ColorMapIndexedPart 4
#define ColorMapNewStyle 8
#define ColorMapPresent 1
#define FixedPt1 0x4000
#define FormBitsIndex 0
#define FormDepthIndex 3
#define FormHeightIndex 2
#define FormWidthIndex 1
#define GreenIndex 1
#define OpTableSize 46
#define RedIndex 0

/*** Function Prototypes ***/
static unsigned int addWordwith(unsigned int sourceWord,
                                unsigned int destinationWord);
static unsigned int alphaBlendConstwith(unsigned int sourceWord,
                                        unsigned int destinationWord);
static unsigned int alphaBlendConstwithpaintMode(unsigned int sourceWord,
                                                 unsigned int destinationWord,
                                                 sqInt paintMode);
static unsigned int alphaBlendScaledwith(unsigned int sourceWord,
                                         unsigned int destinationWord);
static unsigned int alphaBlendUnscaledwith(unsigned int sourceWord,
                                           unsigned int destinationWord);
static unsigned int alphaBlendwith(unsigned int sourceWord,
                                   unsigned int destinationWord);
static unsigned int alphaPaintConstwith(unsigned int sourceWord,
                                        unsigned int destinationWord);
static unsigned int alphaScalewith(unsigned int sourceWord,
                                   unsigned int destinationWord);
static sqInt alphaSourceBlendBits16(void);
static sqInt alphaSourceBlendBits32(void);
static sqInt alphaSourceBlendBits8(void);
static unsigned int alphaUnscalewith(unsigned int sourceWord,
                                     unsigned int destinationWord);
static unsigned int bitAndInvertwith(unsigned int sourceWord,
                                     unsigned int destinationWord);
static unsigned int bitAndwith(unsigned int sourceWord,
                               unsigned int destinationWord);
static unsigned int bitInvertAndInvertwith(unsigned int sourceWord,
                                           unsigned int destinationWord);
static unsigned int bitInvertAndwith(unsigned int sourceWord,
                                     unsigned int destinationWord);
static unsigned int bitInvertDestinationwith(unsigned int sourceWord,
                                             unsigned int destinationWord);
static unsigned int bitInvertOrInvertwith(unsigned int sourceWord,
                                          unsigned int destinationWord);
static unsigned int bitInvertOrwith(unsigned int sourceWord,
                                    unsigned int destinationWord);
static unsigned int bitInvertSourcewith(unsigned int sourceWord,
                                        unsigned int destinationWord);
static unsigned int bitInvertXorwith(unsigned int sourceWord,
                                     unsigned int destinationWord);
static unsigned int bitOrInvertwith(unsigned int sourceWord,
                                    unsigned int destinationWord);
static unsigned int bitOrwith(unsigned int sourceWord,
                              unsigned int destinationWord);
static unsigned int bitXorwith(unsigned int sourceWord,
                               unsigned int destinationWord);
static unsigned int clearWordwith(unsigned int sourceWord,
                                  unsigned int destinationWord);
static sqInt clipRange(void);
EXPORT(sqInt) copyBits(void);
static sqInt copyBitsFastPathSpecialised(void);
EXPORT(sqInt) copyBitsFromtoat(sqInt startX, sqInt stopX, sqInt yValue);
static sqInt copyBitsLockedAndClipped(void);
static sqInt copyBitsRule41Test(void);
extern void copyBitsFallback(operation_t *op, unsigned int flags);
static sqInt copyLoop(void);
static sqInt copyLoopNoSource(void);
static sqInt copyLoopPixMap(void);
static unsigned int *default8To32Table(void);
static unsigned int destinationWordwith(unsigned int sourceWord,
                                        unsigned int destinationWord);
static sqInt fetchIntOrFloatofObjectifNil(sqInt fieldIndex, sqInt objectPointer,
                                          sqInt defaultValue);
static unsigned int fixAlphawith(unsigned int sourceWord,
                                 unsigned int destinationWord);
EXPORT(const char *) getModuleName(void);
static sqInt initBBOpTable(void);
static sqInt initDither8Lookup(void);
EXPORT(sqInt) initialiseModule(void);
EXPORT(sqInt) loadBitBltFrom(sqInt bbObj);
static sqInt loadBitBltFromwarping(sqInt bbObj, sqInt aBool);
static sqInt loadSurfacePlugin(void);
static sqInt lockSurfaces(void);
EXPORT(sqInt) moduleUnloaded(char *aModuleName);
static sqInt OLDrgbDiffwith(sqInt sourceWord, sqInt destinationWord);
static sqInt OLDtallyIntoMapwith(sqInt sourceWord, sqInt destinationWord);
static unsigned int partitionedAddtonBitscomponentMaskcarryOverflowMask(
    unsigned int word1, unsigned int word2, sqInt nBits,
    unsigned int componentMask, unsigned int carryOverflowMask);
static unsigned int partitionedANDtonBitsnPartitions(unsigned int word1,
                                                     unsigned int word2,
                                                     sqInt nBits, sqInt nParts);
static unsigned int partitionedMaxwithnBitsnPartitions(unsigned int word1,
                                                       unsigned int word2,
                                                       sqInt nBits,
                                                       sqInt nParts);
static unsigned int partitionedMinwithnBitsnPartitions(unsigned int word1,
                                                       unsigned int word2,
                                                       sqInt nBits,
                                                       sqInt nParts);
static unsigned int partitionedMulwithnBitswordBits(unsigned int word1,
                                                    unsigned int word2,
                                                    sqInt nBits,
                                                    sqInt wordBits);
static unsigned int partitionedSubfromnBitsnPartitions(unsigned int word1,
                                                       unsigned int word2,
                                                       sqInt nBits,
                                                       sqInt nParts);
static unsigned int pixClearwith(unsigned int sourceWord,
                                 unsigned int destinationWord);
static unsigned int pixMaskwith(unsigned int sourceWord,
                                unsigned int destinationWord);
static unsigned int pixPaintwith(unsigned int sourceWord,
                                 unsigned int destinationWord);
static unsigned int pixSwapwith(unsigned int sourceWord, unsigned int destWord);
EXPORT(sqInt) primitiveCompareColors(void);
EXPORT(sqInt) primitiveCopyBits(void);
EXPORT(sqInt) primitiveDisplayString(void);
EXPORT(sqInt) primitiveDrawLoop(void);
EXPORT(sqInt) primitivePixelValueAt(void);
EXPORT(sqInt) primitivePixelValueAtPut(void);
EXPORT(sqInt) primitiveWarpBits(void);
static sqInt reloadDestAndSourceForms(void);
static unsigned int rgbAddwith(unsigned int sourceWord,
                               unsigned int destinationWord);
static sqInt rgbComponentAlpha16(void);
static sqInt rgbComponentAlpha32(void);
static sqInt rgbComponentAlpha32with(sqInt sourceWord, sqInt destinationWord);
static sqInt rgbComponentAlpha8(void);
static sqInt rgbComponentAlphawith(sqInt sourceWord, sqInt destinationWord);
static unsigned int rgbDiffwith(unsigned int sourceWord,
                                unsigned int destinationWord);
static sqInt rgbMapfromto(sqInt sourcePixel, sqInt nBitsIn, sqInt nBitsOut);
static unsigned int rgbMaxwith(unsigned int sourceWord,
                               unsigned int destinationWord);
static unsigned int rgbMinInvertwith(unsigned int wordToInvert,
                                     unsigned int destinationWord);
static unsigned int rgbMinwith(unsigned int sourceWord,
                               unsigned int destinationWord);
static unsigned int rgbMulwith(unsigned int sourceWord,
                               unsigned int destinationWord);
static unsigned int rgbSubwith(unsigned int sourceWord,
                               unsigned int destinationWord);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);
static sqInt setupColorMasks(void);
static sqInt setupColorMasksFromto(sqInt srcBits, sqInt targetBits);
static unsigned int sourceWordwith(unsigned int sourceWord,
                                   unsigned int destinationWord);
static unsigned int subWordwith(unsigned int sourceWord,
                                unsigned int destinationWord);
static unsigned int tallyIntoMapwith(unsigned int sourceWord,
                                     unsigned int destinationWord);
static sqInt unlockSurfaces(void);
static sqInt warpLoop(void);
static sqInt
warpPickSmoothPixelsxDeltahyDeltahxDeltavyDeltavsourceMapsmoothingdstShiftInc(
    sqInt nPixels, sqInt xDeltah, sqInt yDeltah, sqInt xDeltav, sqInt yDeltav,
    sqInt sourceMap, sqInt n, sqInt dstShiftInc);

/*** Variables ***/
static sqInt affectedB;
static sqInt affectedL;
static sqInt affectedR;
static sqInt affectedT;
static sqInt bitBltIsReceiver;
static sqInt bitBltOop;
static sqInt bitCount;
static sqInt clipHeight;
static sqInt clipWidth;
static sqInt clipX;
static sqInt clipY;
static sqInt cmBitsPerColor;
static sqInt cmFlags;
static unsigned int *cmLookupTable;
static sqInt cmMask;
static unsigned int *cmMaskTable;
static int *cmShiftTable;
static sqInt combinationRule;
static sqInt componentAlphaModeAlpha;
static sqInt componentAlphaModeColor;
static sqInt destBits;
static sqInt destDelta;
static sqInt destForm;
static usqInt destIndex;
static sqInt destMask;
static sqInt destPPW;
static sqInt destX;
static sqInt destY;
static unsigned char dither8Lookup[4096];
static const int ditherMatrix4x4[16] = {0, 8,  2, 10, 12, 4, 14, 6,
                                        3, 11, 1, 9,  15, 7, 13, 5};
static const int ditherThresholds16[8] = {0, 2, 4, 6, 8, 12, 14, 16};
static const int ditherValues16[32] = {
    0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};
static sqInt dstBitShift;
static sqInt dx;
static sqInt dy;
static usqInt endOfDestination;
static usqInt endOfSource;
static unsigned char *gammaLookupTable;
static sqInt halftoneBase;
static sqInt halftoneForm;
static sqInt halftoneHeight;
static sqInt hasSurfaceLock;
static sqInt hDir;
static sqInt height;

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*byteSizeOf)(sqInt oop);
static sqInt (*failed)(void);
static sqInt (*fetchIntegerofObject)(sqInt fieldIndex, sqInt objectPointer);
static sqInt (*fetchLong32ofObject)(sqInt fieldIndex, sqInt oop);
static sqInt (*fetchPointerofObject)(sqInt index, sqInt oop);
static void *(*firstIndexableField)(sqInt oop);
static double (*floatValueOf)(sqInt oop);
#if !defined(integerObjectOf)
static sqInt (*integerObjectOf)(sqInt value);
#endif
#if !defined(integerValueOf)
static sqInt (*integerValueOf)(sqInt oop);
#endif
static void *(*ioLoadFunctionFrom)(char *functionName, char *moduleName);
static sqInt (*isArray)(sqInt oop);
static sqInt (*isBytes)(sqInt oop);
#if !defined(isIntegerObject)
static sqInt (*isIntegerObject)(sqInt objectPointer);
#endif
static sqInt (*isPointers)(sqInt oop);
static sqInt (*isPositiveMachineIntegerObject)(sqInt oop);
static sqInt (*isWords)(sqInt oop);
static sqInt (*isWordsOrBytes)(sqInt oop);
static sqInt (*methodArgumentCount)(void);
static sqInt (*methodReturnInteger)(sqInt integer);
static sqInt (*methodReturnReceiver)(void);
static sqInt (*methodReturnValue)(sqInt oop);
static sqInt (*nilObject)(void);
static sqInt (*pop)(sqInt nItems);
static sqInt (*positive32BitIntegerFor)(unsigned int integerValue);
static usqInt (*positive32BitValueOf)(sqInt oop);
static usqLong (*positive64BitValueOf)(sqInt oop);
static sqInt (*primitiveFail)(void);
static sqInt (*primitiveFailFor)(sqInt reasonCode);
static sqInt (*showDisplayBitsLeftTopRightBottom)(sqInt aForm, sqInt l, sqInt t,
                                                  sqInt r, sqInt b);
static sqInt (*slotSizeOf)(sqInt oop);
static sqInt (*stackIntegerValue)(sqInt offset);
static sqInt (*stackObjectValue)(sqInt offset);
static sqInt (*stackValue)(sqInt offset);
static sqInt (*statNumGCs)(void);
static sqInt (*storeIntegerofObjectwithValue)(sqInt index, sqInt oop,
                                              sqInt integer);
static usqInt (*storeLong32ofObjectwithValue)(sqInt fieldIndex, sqInt oop,
                                              usqInt anInteger);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt byteSizeOf(sqInt oop);
extern sqInt failed(void);
extern sqInt fetchIntegerofObject(sqInt fieldIndex, sqInt objectPointer);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 6)
extern sqInt fetchLong32ofObject(sqInt fieldIndex, sqInt oop);
#else
#define fetchLong32ofObject(fieldIndex, oop) 0
#endif
extern sqInt fetchPointerofObject(sqInt index, sqInt oop);
extern void *firstIndexableField(sqInt oop);
extern double floatValueOf(sqInt oop);
#if !defined(integerObjectOf)
extern sqInt integerObjectOf(sqInt value);
#endif
#if !defined(integerValueOf)
extern sqInt integerValueOf(sqInt oop);
#endif
extern void *ioLoadFunctionFrom(char *functionName, char *moduleName);
extern sqInt isArray(sqInt oop);
extern sqInt isBytes(sqInt oop);
#if !defined(isIntegerObject)
extern sqInt isIntegerObject(sqInt objectPointer);
#endif
extern sqInt isPointers(sqInt oop);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 15)
extern sqInt isPositiveMachineIntegerObject(sqInt oop);
#else
#define isPositiveMachineIntegerObject(oop) 0
#endif
extern sqInt isWords(sqInt oop);
extern sqInt isWordsOrBytes(sqInt oop);
extern sqInt methodArgumentCount(void);
extern sqInt methodReturnInteger(sqInt integer);
extern sqInt methodReturnReceiver(void);
extern sqInt methodReturnValue(sqInt oop);
extern sqInt nilObject(void);
extern sqInt pop(sqInt nItems);
extern sqInt positive32BitIntegerFor(unsigned int integerValue);
extern usqInt positive32BitValueOf(sqInt oop);
extern usqLong positive64BitValueOf(sqInt oop);
extern sqInt primitiveFail(void);
extern sqInt primitiveFailFor(sqInt reasonCode);
extern sqInt showDisplayBitsLeftTopRightBottom(sqInt aForm, sqInt l, sqInt t,
                                               sqInt r, sqInt b);
extern sqInt slotSizeOf(sqInt oop);
extern sqInt stackIntegerValue(sqInt offset);
extern sqInt stackObjectValue(sqInt offset);
extern sqInt stackValue(sqInt offset);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 14)
extern sqInt statNumGCs(void);
#else
#define statNumGCs() 0
#endif
extern sqInt storeIntegerofObjectwithValue(sqInt index, sqInt oop,
                                           sqInt integer);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 6)
extern usqInt storeLong32ofObjectwithValue(sqInt fieldIndex, sqInt oop,
                                           usqInt anInteger);
#else
#define storeLong32ofObjectwithValue(fieldIndex, oop, anInteger) 0
#endif
extern
#endif
struct VirtualMachine *interpreterProxy;
static sqInt isWarping;
static sqIntptr_t (*lockSurfaceFn)(sqIntptr_t, int *, int, int, int, int);
static sqInt mask1;
static sqInt mask2;
static int maskTable[33] = {0, 1, 3, 0, 15, 31,    0, 0, 255, 0, 0,
                            0, 0, 0, 0, 0,  65535, 0, 0, 0,   0, 0,
                            0, 0, 0, 0, 0,  0,     0, 0, 0,   0, -1};
static const char *moduleName = "BitBltPlugin VMMaker.oscog-eem.3664 " INT_EXT;
static sqInt noHalftone;
static sqInt noSource;
static sqInt numGCsOnInvocation;
static sqInt nWords;
static void *opTable[46];
static sqInt preload;
static int (*querySurfaceFn)(sqIntptr_t, int *, int *, int *, int *);
static sqInt skew;
static sqInt sourceAlpha;
static sqInt sourceBits;
static sqInt sourceDelta;
static sqInt sourceForm;
static usqInt sourceIndex;
static sqInt sourcePPW;
static sqInt sourceX;
static sqInt sourceY;
static sqInt srcBitShift;
static sqInt sx;
static sqInt sy;
static unsigned char *ungammaLookupTable;
static int (*unlockSurfaceFn)(sqIntptr_t, int, int, int, int);
static sqInt vDir;
static sqInt warpAlignMask;
static sqInt warpAlignShift;
static int warpBitShiftTable[32];
static sqInt warpSrcMask;
static sqInt warpSrcShift;
static sqInt width;
static int bbH;
static int bbW;
static int destDepth;
static int destHeight;
static int destMSB;
static int destPitch;
static int destWidth;
static int sourceDepth;
static int sourceHeight;
static int sourceMSB;
static int sourcePitch;
static int sourceWidth;

/*** Methods ***/

#include "functions/addWordwith.c"

#include "functions/alphaBlendConstwith.c"

#include "functions/alphaBlendConstwithpaintMode.c"

#include "functions/alphaBlendScaledwith.c"

#include "functions/alphaBlendUnscaledwith.c"

#include "functions/alphaBlendwith.c"

#include "functions/alphaPaintConstwith.c"

#include "functions/alphaScalewith.c"

#include "functions/alphaSourceBlendBits16.c"

#include "functions/alphaSourceBlendBits32.c"

#include "functions/alphaSourceBlendBits8.c"

#include "functions/alphaUnscalewith.c"

#include "functions/bitAndInvertwith.c"

#include "functions/bitAndwith.c"

#include "functions/bitInvertAndInvertwith.c"

#include "functions/bitInvertAndwith.c"

#include "functions/bitInvertDestinationwith.c"

#include "functions/bitInvertOrInvertwith.c"

#include "functions/bitInvertOrwith.c"

#include "functions/bitInvertSourcewith.c"

#include "functions/bitInvertXorwith.c"

#include "functions/bitOrInvertwith.c"

#include "functions/bitOrwith.c"

#include "functions/bitXorwith.c"

#include "functions/clearWordwith.c"

#include "functions/clipRange.c"

#include "functions/copyBits.c"

#include "functions/copyBitsFastPathSpecialised.c"

#include "functions/copyBitsFromtoat.c"

#include "functions/copyBitsLockedAndClipped.c"

#include "functions/copyBitsRule41Test.c"

#include "functions/copyBitsFallback.c"

#include "functions/copyLoop.c"

#include "functions/copyLoopNoSource.c"

#include "functions/copyLoopPixMap.c"

#include "functions/default8To32Table.c"

#include "functions/destinationWordwith.c"

#include "functions/fetchIntOrFloatofObjectifNil.c"

#include "functions/fixAlphawith.c"

#include "functions/getModuleName.c"

#include "functions/initBBOpTable.c"

#include "functions/initDither8Lookup.c"

#include "functions/initialiseModule.c"

#include "functions/loadBitBltFrom.c"

#include "functions/loadBitBltFromwarping.c"

#include "functions/loadSurfacePlugin.c"

#include "functions/lockSurfaces.c"

#include "functions/moduleUnloaded.c"

#include "functions/OLDrgbDiffwith.c"

#include "functions/OLDtallyIntoMapwith.c"

#include "functions/partitionedAddtonBitscomponentMaskcarryOverflowMask.c"

#include "functions/partitionedANDtonBitsnPartitions.c"

#include "functions/partitionedMaxwithnBitsnPartitions.c"

#include "functions/partitionedMinwithnBitsnPartitions.c"

#include "functions/partitionedMulwithnBitswordBits.c"

#include "functions/partitionedSubfromnBitsnPartitions.c"

#include "functions/pixClearwith.c"

#include "functions/pixMaskwith.c"

#include "functions/pixPaintwith.c"

#include "functions/pixSwapwith.c"

#include "functions/primitiveCompareColors.c"

#include "functions/primitiveCopyBits.c"

#include "functions/primitiveDisplayString.c"

#include "functions/primitiveDrawLoop.c"

#include "functions/primitivePixelValueAt.c"

#include "functions/primitivePixelValueAtPut.c"

#include "functions/primitiveWarpBits.c"

#include "functions/reloadDestAndSourceForms.c"

#include "functions/rgbAddwith.c"

#include "functions/rgbComponentAlpha16.c"

#include "functions/rgbComponentAlpha32.c"

#include "functions/rgbComponentAlpha32with.c"

#include "functions/rgbComponentAlpha8.c"

#include "functions/rgbComponentAlphawith.c"

#include "functions/rgbDiffwith.c"

#include "functions/rgbMapfromto.c"

#include "functions/rgbMaxwith.c"

#include "functions/rgbMinInvertwith.c"

#include "functions/rgbMinwith.c"

#include "functions/rgbMulwith.c"

#include "functions/rgbSubwith.c"

#include "functions/setInterpreter.c"

#include "functions/setupColorMasks.c"

#include "functions/setupColorMasksFromto.c"

#include "functions/sourceWordwith.c"

#include "functions/subWordwith.c"

#include "functions/tallyIntoMapwith.c"

#include "functions/unlockSurfaces.c"

#include "functions/warpLoop.c"

#include "functions/warpPickSmoothPixelsxDeltahyDeltahxDeltavyDeltavsourceMapsmoothingdstShiftInc.c"

/*** Exports ***/

#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "BitBltPlugin";
void *BitBltPlugin_exports[][3] = {
    {(void *)_m, "copyBits", (void *)copyBits},
    {(void *)_m, "copyBitsFromtoat", (void *)copyBitsFromtoat},
    {(void *)_m, "getModuleName", (void *)getModuleName},
    {(void *)_m, "initialiseModule", (void *)initialiseModule},
    {(void *)_m, "loadBitBltFrom", (void *)loadBitBltFrom},
    {(void *)_m, "moduleUnloaded", (void *)moduleUnloaded},
    {(void *)_m, "primitiveCompareColors\000\001\000",
     (void *)primitiveCompareColors},
    {(void *)_m, "primitiveCopyBits\000\001\000", (void *)primitiveCopyBits},
    {(void *)_m, "primitiveDisplayString\000\001\000",
     (void *)primitiveDisplayString},
    {(void *)_m, "primitiveDrawLoop\000\002\000", (void *)primitiveDrawLoop},
    {(void *)_m, "primitivePixelValueAt\000\002\001",
     (void *)primitivePixelValueAt},
    {(void *)_m, "primitivePixelValueAtPut\000\002\001",
     (void *)primitivePixelValueAtPut},
    {(void *)_m, "primitiveWarpBits\000\001\000", (void *)primitiveWarpBits},
    {(void *)_m, "setInterpreter", (void *)setInterpreter},
    {NULL, NULL, NULL}};

#else // ifdef SQ_BUILTIN_PLUGIN

#if SPURVM
EXPORT(signed short) primitiveCompareColorsMetadata = 0x100;
EXPORT(signed short) primitiveCopyBitsMetadata = 0x100;
EXPORT(signed short) primitiveDisplayStringMetadata = 0x100;
EXPORT(signed short) primitiveDrawLoopMetadata = 0x200;
EXPORT(signed short) primitivePixelValueAtMetadata = 513;
EXPORT(signed short) primitivePixelValueAtPutMetadata = 513;
EXPORT(signed short) primitiveWarpBitsMetadata = 0x100;
#endif // SPURVM

#endif // ifdef SQ_BUILTIN_PLUGIN
