/* Automatically generated by
        SmartSyntaxPluginCodeGenerator VMMaker.oscog-eem.3475 uuid:
   d9ef6856-42d8-4074-bde7-82f1e1d41282 (Compiler-eem.512) from
        ClipboardExtendedPlugin VMMaker.oscog-eem.3475 uuid:
   d9ef6856-42d8-4074-bde7-82f1e1d41282
 */
#if defined(__clang__) || defined(__GNUC__)
static const char __buildInfo[] __attribute__((unused)) =
    "ClipboardExtendedPlugin VMMaker.oscog-eem.3475 uuid: "
    "d9ef6856-42d8-4074-bde7-82f1e1d41282 " __DATE__;
#else
static const char __buildInfo[] =
    "ClipboardExtendedPlugin VMMaker.oscog-eem.3475 uuid: "
    "d9ef6856-42d8-4074-bde7-82f1e1d41282 " __DATE__;
#endif

#include "config.h"
#include "sqMathShim.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"           /* Configuration options */
#include "sqPlatformSpecific.h" /* Platform specific definitions */
#include "sqVirtualMachine.h"   /*  The virtual machine proxy definition */

#include "ClipboardExtendedPlugin.h"
#include "sqMemoryAccess.h"

#define true 1
#define false 0
#define null 0 /* using 'null' because nil is predefined in Think C */
#undef EXPORT
#define EXPORT(returnType) static returnType
#define INT_EXT "(i)"

/*** Function Prototypes ***/
EXPORT(const char *) getModuleName(void);
EXPORT(sqInt) ioAddClipboardData(void);
EXPORT(sqInt) ioClearClipboard(void);
EXPORT(sqInt) ioCreateClipboard(void);
EXPORT(sqInt) ioGetClipboardFormat(void);
EXPORT(sqInt) ioHasClipboardDataInFormat(void);
EXPORT(sqInt) ioReadClipboardData(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);

/*** Variables ***/

extern sqInt byteSizeOf(sqInt oop);
extern sqInt failed(void);
extern void *firstIndexableField(sqInt oop);
#if !defined(integerValueOf)
extern sqInt integerValueOf(sqInt oop);
#endif
extern sqInt isBytes(sqInt oop);
#if !defined(isIntegerObject)
extern sqInt isIntegerObject(sqInt objectPointer);
#endif
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 15)
extern sqInt isPositiveMachineIntegerObject(sqInt oop);
#else
#define isPositiveMachineIntegerObject(oop) 0
#endif
extern sqInt isWordsOrBytes(sqInt oop);
extern sqInt methodReturnBool(sqInt boolean);
extern sqInt methodReturnValue(sqInt oop);
extern sqInt nilObject(void);
extern sqInt pop(sqInt nItems);
extern sqInt positive32BitIntegerFor(unsigned int integerValue);
extern usqInt positive32BitValueOf(sqInt oop);
extern sqInt positive64BitIntegerFor(usqLong integerValue);
extern usqLong positive64BitValueOf(sqInt oop);
extern sqInt primitiveFailFor(sqInt reasonCode);
extern sqInt stackValue(sqInt offset);
extern
struct VirtualMachine *interpreterProxy;
static const char *moduleName =
    "ClipboardExtendedPlugin VMMaker.oscog-eem.3475 " INT_EXT;

/*** Methods ***/

/*	Note: This is hardcoded so it can be run from Squeak.
        The module name is used for validating a module *after*
        it is loaded to check if it does really contain the module
        we're thinking it contains. This is important! */

/* InterpreterPlugin>>#getModuleName */
EXPORT(const char *)
getModuleName(void) { return moduleName; }

/* ClipboardExtendedPlugin>>#ioAddClipboardData:data:dataFormat: */
EXPORT(sqInt)
ioAddClipboardData(void) {
  usqIntptr_t clipboard;
  char *data;
  sqInt dataLength;
  sqInt format;

  if (!((isPositiveMachineIntegerObject(stackValue(2))) &&
        (isWordsOrBytes(stackValue(1))))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  clipboard = (BytesPerOop == 4 ? positive32BitValueOf(stackValue(2))
                                : positive64BitValueOf(stackValue(2)));
  data = firstIndexableField(stackValue(1));
  format = stackValue(0);
  dataLength = byteSizeOf(((sqInt)(sqIntptr_t)(data)-BaseHeaderSize));
  if (isIntegerObject(format)) {
    sqPasteboardPutItemFlavordatalengthformatType(
        ((void *)clipboard), data, dataLength, integerValueOf(format));
  } else {
    if (isBytes(format)) {
      sqPasteboardPutItemFlavordatalengthformatTypeformatLength(
          ((void *)clipboard), data, dataLength, firstIndexableField(format),
          byteSizeOf(format));
    } else {
      primitiveFailFor(PrimErrBadArgument);
    }
  }
  if (!(failed())) {
    pop(3);
  }
  return null;
}

/* ClipboardExtendedPlugin>>#ioClearClipboard: */
EXPORT(sqInt)
ioClearClipboard(void) {
  usqIntptr_t clipboard;

  if (!(isPositiveMachineIntegerObject(stackValue(0)))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  clipboard = (BytesPerOop == 4 ? positive32BitValueOf(stackValue(0))
                                : positive64BitValueOf(stackValue(0)));
  if (!(failed())) {
    sqPasteboardClear(((void *)clipboard));
  }
  if (!(failed())) {
    pop(1);
  }
  return null;
}

/* ClipboardExtendedPlugin>>#ioCreateClipboard */
EXPORT(sqInt)
ioCreateClipboard(void) {
  sqInt _return_value;

  _return_value = /* positiveMachineIntegerFor: */
      (BytesPerWord == 8
           ? positive64BitIntegerFor(((usqInt)(sqCreateClipboard())))
           : positive32BitIntegerFor(((usqInt)(sqCreateClipboard()))));
  if (!(failed())) {
    methodReturnValue(_return_value);
  }
  return null;
}

/* ClipboardExtendedPlugin>>#ioGetClipboardFormat:formatNumber: */
EXPORT(sqInt)
ioGetClipboardFormat(void) {
  usqIntptr_t clipboard;
  sqInt formatNumber;
  sqInt _return_value;

  if (!((isPositiveMachineIntegerObject(stackValue(1))) &&
        (isIntegerObject((formatNumber = stackValue(0)))))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  clipboard = (BytesPerOop == 4 ? positive32BitValueOf(stackValue(1))
                                : positive64BitValueOf(stackValue(1)));
  formatNumber = integerValueOf(formatNumber);
  _return_value = ((sqPasteboardGetItemCount(((void *)clipboard))) > 0
                       ? sqPasteboardCopyItemFlavorsitemNumber(
                             ((void *)clipboard), formatNumber)
                       : nilObject());
  if (!(failed())) {
    methodReturnValue(_return_value);
  }
  return null;
}

/* ClipboardExtendedPlugin>>#ioHasClipboardData:inFormat: */
EXPORT(sqInt)
ioHasClipboardDataInFormat(void) {
  usqIntptr_t clipboard;
  sqInt format;
  sqInt _return_value;

  if (!(isPositiveMachineIntegerObject(stackValue(1)))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  clipboard = (BytesPerOop == 4 ? positive32BitValueOf(stackValue(1))
                                : positive64BitValueOf(stackValue(1)));
  format = stackValue(0);
  if (isIntegerObject(format)) {
    _return_value = sqPasteboardhasDataInFormat(((void *)clipboard),
                                                integerValueOf(format));
    if (!(failed())) {
      methodReturnBool(_return_value);
    }
    return null;
  }
  if (isBytes(format)) {
    _return_value = sqPasteboardhasDataInFormatformatLength(
        ((void *)clipboard), firstIndexableField(format), byteSizeOf(format));
    if (!(failed())) {
      methodReturnBool(_return_value);
    }
    return null;
  }
  primitiveFailFor(PrimErrBadArgument);
  return null;
}

/* ClipboardExtendedPlugin>>#ioReadClipboardData:format: */
EXPORT(sqInt)
ioReadClipboardData(void) {
  usqIntptr_t clipboard;
  sqInt format;
  sqInt _return_value;

  if (!(isPositiveMachineIntegerObject(stackValue(1)))) {
    return primitiveFailFor(PrimErrBadArgument);
  }
  clipboard = (BytesPerOop == 4 ? positive32BitValueOf(stackValue(1))
                                : positive64BitValueOf(stackValue(1)));
  format = stackValue(0);
  if (isIntegerObject(format)) {
    _return_value = sqPasteboardCopyItemFlavorDataformat(
        ((void *)clipboard), integerValueOf(format));
    if (!(failed())) {
      methodReturnValue(_return_value);
    }
    return null;
  }
  if (isBytes(format)) {
    _return_value = sqPasteboardCopyItemFlavorDataformatformatLength(
        ((void *)clipboard), firstIndexableField(format), byteSizeOf(format));
    if (!(failed())) {
      methodReturnValue(_return_value);
    }
    return null;
  }
  primitiveFailFor(PrimErrBadArgument);
  return null;
}

/*	Note: This is coded so that it can be run in Squeak. */

/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine *anInterpreter) {
  sqInt ok;

  interpreterProxy = anInterpreter;

  /* This may seem tautological, but in a real plugin it checks that the VM
     provides the version the plugin was compiled against which is the version
     the plugin expects. */
  ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR)) &&
       ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
  if (ok) {

  }
  return ok;
}

/*** Exports ***/


static char _m[] = "ClipboardExtendedPlugin";
void *ClipboardExtendedPlugin_exports[][3] = {
    {(void *)_m, "getModuleName", (void *)getModuleName},
    {(void *)_m, "ioAddClipboardData\000\001\000", (void *)ioAddClipboardData},
    {(void *)_m, "ioClearClipboard\000\000\000", (void *)ioClearClipboard},
    {(void *)_m, "ioCreateClipboard\000\377\000", (void *)ioCreateClipboard},
    {(void *)_m, "ioGetClipboardFormat\000\000\000",
     (void *)ioGetClipboardFormat},
    {(void *)_m, "ioHasClipboardDataInFormat\000\001\000",
     (void *)ioHasClipboardDataInFormat},
    {(void *)_m, "ioReadClipboardData\000\001\000",
     (void *)ioReadClipboardData},
    {(void *)_m, "setInterpreter", (void *)setInterpreter},
    {NULL, NULL, NULL}};

