/* Automatically generated by
        VMPluginCodeGenerator VMMaker.oscog-eem.3475 uuid:
   d9ef6856-42d8-4074-bde7-82f1e1d41282 (Compiler-eem.512) from
        BMPReadWriterPlugin VMMaker.oscog-eem.3475 uuid:
   d9ef6856-42d8-4074-bde7-82f1e1d41282
 */
#if defined(__clang__) || defined(__GNUC__)
static const char __buildInfo[] __attribute__((unused)) =
    "BMPReadWriterPlugin VMMaker.oscog-eem.3475 uuid: "
    "d9ef6856-42d8-4074-bde7-82f1e1d41282 " __DATE__;
#else
static const char __buildInfo[] =
    "BMPReadWriterPlugin VMMaker.oscog-eem.3475 uuid: "
    "d9ef6856-42d8-4074-bde7-82f1e1d41282 " __DATE__;
#endif

#include "config.h"
#include "sqMathShim.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"           /* Configuration options */
#include "sqPlatformSpecific.h" /* Platform specific definitions */
#include "sqVirtualMachine.h"   /*  The virtual machine proxy definition */

#include "sqMemoryAccess.h"

#define true 1
#define false 0
#define null 0 /* using 'null' because nil is predefined in Think C */
#undef EXPORT
#define EXPORT(returnType) static returnType
#define INT_EXT "(i)"

/*** Function Prototypes ***/
EXPORT(const char *) getModuleName(void);
EXPORT(sqInt) primitiveRead24BmpLine(void);
EXPORT(sqInt) primitiveWrite24BmpLine(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);

/*** Variables ***/

extern sqInt failed(void);
extern void *firstIndexableField(sqInt oop);
extern sqInt isBytes(sqInt oop);
extern sqInt isWords(sqInt oop);
extern sqInt methodArgumentCount(void);
extern sqInt pop(sqInt nItems);
extern sqInt primitiveFail(void);
extern sqInt slotSizeOf(sqInt oop);
extern sqInt stackIntegerValue(sqInt offset);
extern sqInt stackObjectValue(sqInt offset);
extern
struct VirtualMachine *interpreterProxy;
static const char *moduleName =
    "BMPReadWriterPlugin VMMaker.oscog-eem.3475 " INT_EXT;

/*** Methods ***/

/*	Note: This is hardcoded so it can be run from Squeak.
        The module name is used for validating a module *after*
        it is loaded to check if it does really contain the module
        we're thinking it contains. This is important! */

/* InterpreterPlugin>>#getModuleName */
EXPORT(const char *)
getModuleName(void) { return moduleName; }

/* BMPReadWriterPlugin>>#primitiveRead24BmpLine */
EXPORT(sqInt)
primitiveRead24BmpLine(void) {
  unsigned int *formBits;
  sqInt formBitsIndex;
  sqInt formBitsOop;
  sqInt formBitsSize;
  unsigned char *pixelLine;
  sqInt pixelLineOop;
  sqInt pixelLineSize;
  sqInt width;

  if (!((methodArgumentCount()) == 4)) {
    return primitiveFail();
  }
  width = stackIntegerValue(0);
  if (width <= 0) {
    return primitiveFail();
  }
  formBitsIndex = stackIntegerValue(1);
  formBitsOop = stackObjectValue(2);
  pixelLineOop = stackObjectValue(3);
  if (failed()) {
    return null;
  }
  if (!(isWords(formBitsOop))) {
    return primitiveFail();
  }
  if (!(isBytes(pixelLineOop))) {
    return primitiveFail();
  }
  formBitsSize = slotSizeOf(formBitsOop);
  formBits = firstIndexableField(formBitsOop);
  pixelLineSize = slotSizeOf(pixelLineOop);
  pixelLine = firstIndexableField(pixelLineOop);
  if (!((((formBitsIndex + width) - 1) <= formBitsSize) &&
        ((width * 3) <= pixelLineSize))) {
    return primitiveFail();
  }

  /* do the actual work */

  formBits += formBitsIndex - 1;
  while (width--) {
    unsigned int rgb;
    rgb = (*pixelLine++);
    rgb += (*pixelLine++) << 8;
    rgb += (*pixelLine++) << 16;
    if (rgb)
      rgb |= 0xFF000000;
    else
      rgb |= 0xFF000001;
    *formBits++ = rgb;
  }
  pop(4);
  return 0;
}

/* BMPReadWriterPlugin>>#primitiveWrite24BmpLine */
EXPORT(sqInt)
primitiveWrite24BmpLine(void) {
  unsigned int *formBits;
  sqInt formBitsIndex;
  sqInt formBitsOop;
  sqInt formBitsSize;
  unsigned char *pixelLine;
  sqInt pixelLineOop;
  sqInt pixelLineSize;
  sqInt width;

  if (!((methodArgumentCount()) == 4)) {
    return primitiveFail();
  }
  width = stackIntegerValue(0);
  if (width <= 0) {
    return primitiveFail();
  }
  formBitsIndex = stackIntegerValue(1);
  formBitsOop = stackObjectValue(2);
  pixelLineOop = stackObjectValue(3);
  if (failed()) {
    return null;
  }
  if (!(isWords(formBitsOop))) {
    return primitiveFail();
  }
  if (!(isBytes(pixelLineOop))) {
    return primitiveFail();
  }
  formBitsSize = slotSizeOf(formBitsOop);
  formBits = firstIndexableField(formBitsOop);
  pixelLineSize = slotSizeOf(pixelLineOop);
  pixelLine = firstIndexableField(pixelLineOop);
  if (!((((formBitsIndex + width) - 1) <= formBitsSize) &&
        ((width * 3) <= pixelLineSize))) {
    return primitiveFail();
  }

  /* do the actual work. Read 32 bit at a time from formBits, and store the low
     order 24 bits or each word into pixelLine in little endian order. */

  formBits += formBitsIndex - 1;

  while (width--) {
    unsigned int rgb;
    rgb = *formBits++;
    (*pixelLine++) = (rgb) & 0xFF;
    (*pixelLine++) = (rgb >> 8) & 0xFF;
    (*pixelLine++) = (rgb >> 16) & 0xFF;
  }
  pop(4);
  return 0;
}

/*	Note: This is coded so that it can be run in Squeak. */

/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine *anInterpreter) {
  sqInt ok;

  interpreterProxy = anInterpreter;

  /* This may seem tautological, but in a real plugin it checks that the VM
     provides the version the plugin was compiled against which is the version
     the plugin expects. */
  ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR)) &&
       ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
  if (ok) {

  }
  return ok;
}

/*** Exports ***/


static char _m[] = "BMPReadWriterPlugin";
void *BMPReadWriterPlugin_exports[][3] = {
    {(void *)_m, "getModuleName", (void *)getModuleName},
    {(void *)_m, "primitiveRead24BmpLine\000\001\000",
     (void *)primitiveRead24BmpLine},
    {(void *)_m, "primitiveWrite24BmpLine\000\001\000",
     (void *)primitiveWrite24BmpLine},
    {(void *)_m, "setInterpreter", (void *)setInterpreter},
    {NULL, NULL, NULL}};

