SRCDIRS:=$(PLUGINSRCDIR)/SecurityPlugin/unix
INCDIRS:=$(PLUGINSRCDIR)/FilePlugin/cross $(PLUGINSRCDIR)/SecurityPlugin/cross
LIBSRC:=SecurityPlugin.c sqUnixSecurity.c

include ../common/Makefile.plugin
